import { collider } from "../../../utils/collider";
import { util } from "../../../utils/util";
import { v2 } from "../../../utils/v2";
import type { MapObjectDef, ObstacleDef } from "../../mapObjectsTyping";
import { autoLoot, tierLoot } from "../mapObjectHelpers";

//
// Purely Loot Obstacles - Crates, Chests, Cases, Airdrops, Etc.
// Furniture and caches that drop loot not included here
//

function createCrate<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "crate",
        scale: { createMin: 1, createMax: 1, destroy: 0.5 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.25, 2.25)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 75,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: true, color: 0x663300, scale: 0.875 },
        terrain: { grass: true, beach: true, riverShore: true },
        img: {
            sprite: "map-crate-01.img",
            residue: "map-crate-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_crate_bullet",
            punch: "wood_crate_bullet",
            explode: "crate_break_02",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}

function createCase<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "crate",
        scale: { createMin: 1, createMax: 1, destroy: 0.8 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.25, 1.6)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 75,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-case-deagle-01.img",
            residue: "map-crate-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_crate_bullet",
            punch: "wood_crate_bullet",
            explode: "crate_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}

function createChest<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "crate",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.25, 1.6)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 140,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_chest", 3, 4)],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-chest-01.img",
            residue: "map-crate-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_crate_bullet",
            punch: "wood_crate_bullet",
            explode: "crate_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}

function createRiverChest<T extends ObstacleDef>(e: Partial<T>): T {
    const t = createChest({
        collision: collider.createAabbExtents(v2.create(0, 0.8), v2.create(2.25, 0.8)),
        mapObstacleBounds: [
            collider.createAabbExtents(v2.create(0, 0.8), v2.create(2.25, 1.6)),
        ],
        terrain: { river: { centerWeight: 1 } },
    });
    return util.mergeDeep(t, e || {});
}

function createAirdrop<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        obstacleType: "airdrop",
        dropCollision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.5, 2.5)),
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.5, 2.5)),
        airdropCrate: true,
        scale: { destroy: 1 },
        destructible: false,
        health: 200,
        hitParticle: "barrelChip",
        explodeParticle: "airdropCrate02",
        reflectBullets: true,
        loot: [],
        map: { display: false },
        button: {
            interactionRad: 1,
            interactionText: "game-unlock",
            useOnce: true,
            destroyOnUse: true,
            useDelay: 2.5,
            useDir: v2.create(-1, 0),
            useImg: "map-airdrop-04.img",
            useParticle: "airdropCrate03",
            sound: { on: "airdrop_open_01", off: "" },
        },
        sound: {
            bullet: "wall_bullet",
            punch: "metal_punch",
            explode: "airdrop_open_02",
        },
    } as unknown as Partial<ObstacleDef>;
    return util.mergeDeep(createCrate(t), e || {});
}

function createClassCrate<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "crate",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createCircle(v2.create(0, 0), 2.1),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 150,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: false },
        terrain: { grass: true, beach: true, riverShore: true },
        img: {
            sprite: "map-class-crate-01.img",
            residue: "map-class-crate-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_crate_bullet",
            punch: "wood_crate_bullet",
            explode: "crate_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}

const CrateDefs = {
    case_01: createCase({ loot: [autoLoot("deagle", 1, { preloadGuns: true })] }),
    case_02: createCase({
        img: { sprite: "map-case-deagle-02.img" },
        loot: [autoLoot("deagle_dual", 1, { preloadGuns: true })],
    }),
    case_03: createCase({
        health: 140,
        img: {
            sprite: "map-case-hatchet-01.img",
            residue: "map-case-hatchet-res-01.img",
        },
        loot: [tierLoot("tier_hatchet", 1, 1)],
        hitParticle: "blackChip",
    }),
    case_04: createCase({
        health: 140,
        img: {
            sprite: "map-case-flare-01.img",
            residue: "map-case-flare-res-01.img",
        },
        loot: [autoLoot("flare_gun", 1)],
        hitParticle: "blackChip",
        map: { display: true, color: 0x6b3500, scale: 0.85 },
    }),
    case_05: createCase({
        health: 140,
        img: {
            sprite: "map-case-meteor-01.img",
            residue: "map-case-meteor-res-01.img",
        },
        loot: [
            autoLoot("flare_gun", 1),
            autoLoot("strobe", 1),
            autoLoot("strobe", 1),
            autoLoot("strobe", 1),
            autoLoot("strobe", 1),
        ],
        hitParticle: "blackChip",
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    case_06: createCase({
        health: 140,
        img: { sprite: "map-case-chrys-01.img" },
        loot: [tierLoot("tier_chest", 2, 3), tierLoot("tier_chrys_case", 1, 1)],
        hitParticle: "blackChip",
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    case_07: createCase({
        health: 200,
        img: { sprite: "map-case-ring-01.img" },
        loot: [tierLoot("tier_ring_case", 1, 1)],
        hitParticle: "blackChip",
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    case_07de: createCase({
        health: 200,
        img: { sprite: "map-case-ring-02.img" },
        loot: [
            tierLoot("tier_airdrop_crimson", 1, 1),
            autoLoot("backpack03", 1),
            tierLoot("tier_crimson_perks", 1, 1),
            autoLoot("4xscope", 1),
        ],
        hitParticle: "blackChip",
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    case_08: createCase({
        health: 140,
        img: { sprite: "map-case-crow-01.img" },
        loot: [
            tierLoot("tier_armor", 1, 1),
            tierLoot("tier_medical", 1, 2),
            tierLoot("tier_crow_case_melee", 1, 1),
            tierLoot("tier_crow_case_skin", 1, 1),
        ],
        hitParticle: "blackChip",
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    case_08sv: createCase({
        health: 140,
        img: { sprite: "map-case-crow-01.img" },
        loot: [
            tierLoot("tier_armor", 1, 1),
            tierLoot("tier_medical", 1, 2),
            tierLoot("tier_perks", 1, 1),
            tierLoot("tier_crow_case_melee", 1, 1),
            tierLoot("tier_crow_case_skin", 1, 1),
        ],
        hitParticle: "blackChip",
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    case_09: createCase({
        health: 140,
        img: {
            sprite: "map-case-twins-01.img",
            residue: "map-case-hatchet-res-01.img",
        },
        loot: [
            tierLoot("tier_guns_rare_classless", 1, 1),
            autoLoot("healthkit", 1),
            autoLoot("soda", 2),
            autoLoot("4xscope", 1),
            autoLoot("chest02", 1),
            autoLoot("backpack02", 1),
            autoLoot("naginata_daemon", 1),
        ],
        hitParticle: "blackChip",
    }),
    chest_01: createChest({
        loot: [
            tierLoot("tier_chest", 3, 4),
            tierLoot("tier_pirate_melee", 1, 1),
            tierLoot("tier_pirate_outfits", 1, 1),
        ],
    }),
    chest_01cb: createChest({
        loot: [tierLoot("tier_chest", 3, 4), tierLoot("tier_pirate_melee", 1, 1)],
    }),
    chest_02: createChest({
        img: { sprite: "map-chest-02.img" },
        loot: [tierLoot("tier_chest", 2, 2)],
        map: { display: true, color: 7025920, scale: 0.85 },
    }),
    chest_03: createRiverChest({
        img: { sprite: "map-chest-03.img" },
        loot: [tierLoot("tier_chest", 3, 5), autoLoot("outfitWaterElem", 1)],
    }),
    chest_03cb: createRiverChest({
        img: { sprite: "map-chest-03.img" },
        loot: [tierLoot("tier_chest", 3, 5)],
    }),
    chest_03d: createRiverChest({
        img: { sprite: "map-chest-03d.img" },
        loot: [tierLoot("tier_chest", 3, 5), autoLoot("outfitWaterElem", 1)],
    }),
    chest_03f: createRiverChest({
        img: { sprite: "map-chest-03f.img" },
        loot: [tierLoot("tier_chest", 3, 5), autoLoot("outfitKhaki", 1)],
    }),
    chest_03sv: createRiverChest({
        img: { sprite: "map-chest-03sv.img" },
        loot: [tierLoot("tier_chest", 3, 5), autoLoot("outfitWaterElem", 1)],
    }),
    chest_03x: createRiverChest({
        img: { sprite: "map-chest-03x.img" },
        loot: [tierLoot("tier_chest", 3, 5), autoLoot("outfitWaterElem", 1)],
    }),
    chest_03tr: createRiverChest({
        img: { sprite: "map-chest-03tr.img" },
        loot: [tierLoot("tier_chest", 3, 5), autoLoot("outfitWaterElem", 1)],
    }),
    chest_04: createChest({
        health: 200,
        img: { sprite: "map-case-basement-01.img" },
        loot: [
            tierLoot("tier_noir_outfit", 1, 1),
            tierLoot("tier_chest_04", 1, 1),
            autoLoot("glock_dual", 1),
            autoLoot("smoke", 4),
        ],
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    chest_04d: createChest({
        health: 200,
        img: { sprite: "map-case-basement-01.img" },
        loot: [
            tierLoot("tier_noir_outfit", 1, 1),
            tierLoot("tier_chest_04", 1, 1),
            autoLoot("9mm", 300),
            autoLoot("smoke", 4),
            autoLoot("backpack02", 1),
        ],
        map: { display: false, color: 0x6b3500, scale: 0.85 },
    }),
    crate_01: createCrate({}),
    crate_01x: createCrate({ img: { sprite: "map-crate-01x.img" } }),
    crate_02: createCrate({
        health: 140,
        loot: [tierLoot("tier_soviet", 3, 5)],
        map: { display: false },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-02.img" },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_02sv: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_soviet", 4, 5),
            tierLoot("tier_world", 1, 1),
            tierLoot("tier_medical", 1, 1),
        ],
        map: { display: true, color: 0xffc000 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-02sv.img" },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_02sv_lake: createCrate({
        health: 140,
        loot: [tierLoot("tier_soviet", 5, 6), tierLoot("tier_medical", 1, 1)],
        map: { display: true, color: 0xffc000 },
        img: { sprite: "map-crate-02sv.img" },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_02x: createCrate({
        health: 140,
        loot: [tierLoot("tier_soviet", 3, 5)],
        map: { display: false },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-02x.img" },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_02f: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_guns", 3, 3, { preloadGuns: true }),
            tierLoot("tier_armor", 2, 2),
            tierLoot("tier_packs", 1, 1),
        ],
        map: { display: true, color: 0xcc0000 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-02f.img" },
        sound: { explode: "crate_break_01" },
        teamId: 1,
    } as unknown as Partial<ObstacleDef>),
    crate_02d: createCrate({
        health: 140,
        loot: [
            autoLoot("m1014", 1),
            autoLoot("helmet03_lt_aged", 1),
            autoLoot("outfitRedLeaderAged", 1),
            autoLoot("machete_taiga", 1),
        ],
        map: { display: true, color: 0xcc0000 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-02f.img" },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_03: createCrate({
        health: 100,
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.575, 1.575)),
        loot: [tierLoot("tier_throwables", 2, 4), tierLoot("tier_fragtastic", 1, 1)],
        map: { color: 0x4d4d1e, scale: 0.875 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-03.img", scale: 0.35 },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_03x: createCrate({
        health: 100,
        hitParticle: "glassChip",
        explodeParticle: ["glassPlank"],
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.575, 1.575)),
        loot: [autoLoot("snowball", 4), autoLoot("snowball", 4), autoLoot("snowball", 4)],
        map: { color: 0x7c77, scale: 0.875 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-03x.img", scale: 0.35 },
        sound: { explode: "crate_break_02" },
    } as unknown as Partial<ObstacleDef>),
    crate_04: createCrate({
        health: 225,
        destructible: true,
        armorPlated: true,
        hitParticle: "greenChip",
        loot: [tierLoot("tier_ammo_crate", 1, 1)],
        map: { display: true, color: 0x537054, scale: 0.875 },
        img: { sprite: "map-crate-04.img" },
        sound: {
            bullet: "ammo_crate_bullet",
            punch: "ammo_crate_bullet",
            explode: "crate_break_01",
        },
    }),
    crate_05: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2, 2)),
        destructible: false,
        hitParticle: "goldChip",
        loot: [],
        map: { display: false },
        img: { sprite: "map-crate-05.img" },
        sound: {
            bullet: "wall_brick_bullet",
            punch: "wall_brick_bullet",
        },
    }),
    crate_06: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.25, 1.1)),
        health: 175,
        destructible: true,
        armorPlated: true,
        hitParticle: "greenChip",
        loot: [tierLoot("tier_ammo", 1, 1)],
        map: { display: true },
        img: { sprite: "map-crate-06.img" },
        sound: {
            bullet: "ammo_crate_bullet",
            punch: "ammo_crate_bullet",
        },
    }),
    crate_07: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_surviv", 4, 5),
            autoLoot("ak47", 1),
            autoLoot("ak47", 1),
            autoLoot("ak47", 1),
            autoLoot("ak47", 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
        ],
        img: { sprite: "map-crate-07.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_07b: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_armor", 4, 5),
            autoLoot("mp220", 1),
            autoLoot("mp220", 1),
            autoLoot("bar", 1),
            autoLoot("bar", 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
        ],
        img: { sprite: "map-crate-07.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_07sv: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_surviv", 4, 5),
            autoLoot("svd", 1),
            autoLoot("svd", 1),
            autoLoot("blr", 1),
            autoLoot("blr", 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
            tierLoot("tier_khaki_outfit", 1, 1),
        ],
        img: { sprite: "map-crate-07.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_08: createCrate({
        health: 140,
        loot: [tierLoot("tier_surviv", 2, 3)],
        map: { display: false },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-08.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_09: createCrate({
        health: 140,
        loot: [tierLoot("tier_chest", 1, 2), tierLoot("tier_conch", 1, 1)],
        map: { display: false },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-09.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_09bh: createCrate({
        health: 140,
        loot: [tierLoot("tier_soviet", 3, 5), tierLoot("tier_outfits", 1, 1)],
        map: { display: false },
        img: { sprite: "map-crate-09.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_10: createCrate({
        health: 200,
        scale: { destroy: 0.75 },
        loot: [
            tierLoot("tier_airdrop_uncommon", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_outfits", 1, 1),
            tierLoot("tier_airdrop_melee", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-10.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_11: createCrate({
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_rare", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_outfits", 1, 1),
            tierLoot("tier_airdrop_melee", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-11.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_11h: createCrate({
        collision: collider.createCircle(v2.create(0, 0), 2.25),
        isDecalAnchor: true,
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_rare", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_outfits", 1, 1),
            tierLoot("tier_outfits", 1, 1),
            tierLoot("tier_airdrop_melee", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 1),
            tierLoot("tier_airdrop_xp", 2, 2),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-11h.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_10sv: createCrate({
        health: 200,
        scale: { destroy: 0.75 },
        loot: [
            tierLoot("tier_airdrop_uncommon", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_outfits", 1, 1),
            tierLoot("tier_airdrop_melee", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 1),
            tierLoot("tier_perks", 1, 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-10.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_11sv: createCrate({
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_rare", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_outfits", 1, 1),
            tierLoot("tier_airdrop_melee", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 1),
            tierLoot("tier_perks", 2, 2),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-11.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_11de: createCrate({
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_rare", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_outfits", 1, 1),
            tierLoot("tier_airdrop_melee", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 1),
            tierLoot("tier_perks", 1, 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-11.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_11tr: createCrate({
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_rare", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_outfits", 1, 1),
            tierLoot("tier_airdrop_melee", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 1),
            tierLoot("tier_airdrop_xp", 2, 2),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-11.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_12: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3.5, 3.5)),
        scale: { destroy: 0.75 },
        health: 500,
        loot: [
            tierLoot("tier_airdrop_rare", 2, 2, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_uncommon", 7, 8, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_armor", 5, 6),
            tierLoot("tier_medical", 12, 15),
            tierLoot("tier_airdrop_scopes", 7, 8),
            tierLoot("tier_airdrop_outfits", 3, 4),
            tierLoot("tier_airdrop_melee", 6, 7),
            tierLoot("tier_airdrop_ammo", 10, 12),
            tierLoot("tier_airdrop_throwables", 6, 8),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-12.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_12po: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3.5, 3.5)),
        scale: { destroy: 0.75 },
        health: 500,
        loot: [
            tierLoot("tier_airdrop_rare", 2, 2, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_uncommon", 7, 8, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_armor", 5, 6),
            tierLoot("tier_medical", 12, 15),
            tierLoot("tier_airdrop_scopes", 7, 8),
            tierLoot("tier_airdrop_outfits", 3, 4),
            tierLoot("tier_airdrop_melee", 6, 7),
            tierLoot("tier_airdrop_ammo", 10, 12),
            tierLoot("tier_airdrop_throwables", 6, 8),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-12.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_12dev: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3.5, 3.5)),
        scale: { destroy: 0.75 },
        health: 1100,
        loot: [
            tierLoot("tier_dev_guns", 20, 20, {
                preloadGuns: true,
            }),
            tierLoot("tier_dev_melee", 6, 7),
            autoLoot("snowball", 100),
            autoLoot("bandage", 1),
            autoLoot("smoke", 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-13.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_13: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3.5, 3.5)),
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_mythic", 3, 4, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_rare", 5, 5, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_armor", 6, 8),
            tierLoot("tier_medical", 12, 15),
            tierLoot("tier_airdrop_scopes", 7, 8),
            tierLoot("tier_airdrop_faction_outfits", 1, 2),
            tierLoot("tier_airdrop_melee", 2, 3),
            tierLoot("tier_airdrop_faction_melee", 3, 3),
            tierLoot("tier_airdrop_ammo", 10, 12),
            tierLoot("tier_airdrop_throwables", 6, 8),
            autoLoot("strobe", 1),
            autoLoot("strobe", 1),
            autoLoot("strobe", 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-13.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_13po: createCrate({
        // TODO: same as crate 12
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3.5, 3.5)),
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_potato", 2, 2),
            tierLoot("tier_airdrop_mythic", 3, 4, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_rare", 5, 5, {
                preloadGuns: true,
            }),
            tierLoot("tier_airdrop_armor", 6, 8),
            tierLoot("tier_medical", 12, 15),
            tierLoot("tier_airdrop_scopes", 7, 8),
            tierLoot("tier_airdrop_faction_outfits", 1, 2),
            tierLoot("tier_airdrop_melee", 2, 3),
            tierLoot("tier_airdrop_faction_melee", 3, 3),
            tierLoot("tier_airdrop_ammo", 10, 12),
            tierLoot("tier_airdrop_throwables", 6, 8),
            autoLoot("strobe", 1),
            autoLoot("strobe", 1),
            autoLoot("strobe", 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-13.img",
            residue: "map-crate-res-03.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_14: createCrate({
        explodeParticle: ["windowBreak", "woodPlank"],
        loot: [tierLoot("tier_throwables", 1, 1)],
        img: { sprite: "map-crate-14.img" },
        sound: { explode: "window_break_02" },
    }),
    crate_14a: createCrate({
        explodeParticle: ["windowBreak", "woodPlank"],
        loot: [tierLoot("tier_soviet", 1, 1)],
        img: { sprite: "map-crate-14a.img" },
        sound: { explode: "window_break_02" },
    }),
    crate_15: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.7, 1.25)),
        health: 100,
        loot: [tierLoot("tier_knives", 4, 4)],
        map: { display: false },
        terrain: { grass: true, beach: true },
        img: { sprite: "map-crate-14.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_16: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.7, 1.25)),
        health: 100,
        loot: [tierLoot("tier_knives", 4, 4)],
        map: { display: false },
        terrain: { grass: true, beach: true },
        img: { sprite: "map-crate-14.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_17: createCrate({
        scale: { destroy: 0.75 },
        health: 200,
        loot: [
            tierLoot("tier_airdrop_crimson", 1, 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 2, 3),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 3, 3),
            tierLoot("tier_airdrop_throwables", 1, 2),
            tierLoot("tier_perks", 0, 1),
            autoLoot("outfitCasanova", 1),
        ],
        map: { display: false },
        img: {
            sprite: "map-crate-17.img",
            residue: "map-crate-res-04.img",
        },
        sound: { explode: "crate_break_01" },
    } as unknown as Partial<ObstacleDef>),
    crate_18: createCrate({
        health: 140,
        loot: [tierLoot("tier_cattle_crate", 2, 3), tierLoot("tier_soviet", 1, 2)],
        map: { display: true, color: 0xc45900, scale: 0.875 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-18.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_19: createCrate({
        health: 140,
        loot: [tierLoot("tier_guns", 1, 3), tierLoot("tier_surviv", 2, 3)],
        map: { display: true, color: 0x44ab00, scale: 0.875 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-19.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_20: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.7, 1.7)),
        health: 75,
        hitParticle: "greenChip",
        explodeParticle: "greenPlank",
        loot: [tierLoot("tier_armor", 1, 1), tierLoot("tier_world", 1, 1)],
        map: { display: true, color: 0x3b452f, scale: 1 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-20.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_21: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_guns", 1, 2),
            tierLoot("tier_snipers", 1, 1),
            tierLoot("tier_cloud_02", 1, 1),
            tierLoot("tier_perks", 1, 1),
        ],
        map: { display: true, color: 0x496f, scale: 0.875 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-21.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_21b: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_guns", 1, 2),
            tierLoot("tier_snipers", 1, 1),
            tierLoot("tier_cloud_02", 1, 1),
            tierLoot("tier_perks", 1, 1),
        ],
        map: { display: false, color: 0x496f, scale: 0.875 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-21.img" },
        sound: { explode: "crate_break_01" },
    }),
    crate_22: createCrate({
        health: 140,
        loot: [
            tierLoot("tier_guns", 3, 3, { preloadGuns: true }),
            tierLoot("tier_armor", 2, 2),
            tierLoot("tier_packs", 1, 1),
        ],
        map: { display: true, color: 32511 },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-22.img" },
        sound: { explode: "crate_break_01" },
        teamId: 2,
    }),
    crate_22d: createCrate({
        health: 140,
        loot: [
            autoLoot("an94", 1),
            autoLoot("helmet03_lt_aged", 1),
            autoLoot("outfitBlueLeaderAged", 1),
            autoLoot("kukri_trad", 1),
        ],
        map: { display: true, color: 0x7eff },
        terrain: { grass: true, beach: false },
        img: { sprite: "map-crate-22.img" },
        sound: { explode: "crate_break_01" },
    }),
    airdrop_crate_01: createAirdrop({
        button: {
            useImg: "map-airdrop-02.img",
            useParticle: "airdropCrate01",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01.img",
            residue: "none",
        },
        destroyType: "crate_10",
        explodeParticle: "airdropCrate02",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_02: createAirdrop({
        button: {
            useImg: "map-airdrop-02.img",
            useParticle: "airdropCrate01",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01.img",
            residue: "none",
        },
        destroyType: "crate_11",
        explodeParticle: "airdropCrate02",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_03: createAirdrop({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4, 4)),
        button: {
            useImg: "map-airdrop-04.img",
            useParticle: "airdropCrate03",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-03.img",
            residue: "none",
        },
        destroyType: "crate_12",
        explodeParticle: "airdropCrate04",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_03po: createAirdrop({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4, 4)),
        button: {
            useImg: "map-airdrop-04.img",
            useParticle: "airdropCrate03",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-03.img",
            residue: "none",
        },
        destroyType: "crate_12po",
        explodeParticle: "airdropCrate04",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_03dev: createAirdrop({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4, 4)),
        button: {
            useImg: "map-airdrop-04.img",
            useParticle: "airdropCrate03",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-03.img",
            residue: "none",
        },
        destroyType: "crate_12dev",
        explodeParticle: "airdropCrate04",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_04: createAirdrop({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4, 4)),
        button: {
            useImg: "map-airdrop-04.img",
            useParticle: "airdropCrate03",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-03.img",
            residue: "none",
        },
        destroyType: "crate_13",
        explodeParticle: "airdropCrate04",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_04po: createAirdrop({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4, 4)),
        button: {
            useImg: "map-airdrop-04.img",
            useParticle: "airdropCrate03",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-03.img",
            residue: "none",
        },
        destroyType: "crate_13po",
        explodeParticle: "airdropCrate04",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_05: createAirdrop({
        button: {
            useImg: "map-airdrop-05.img",
            useParticle: "airdropCrate01",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01.img",
            residue: "none",
        },
        destroyType: "crate_17",
        explodeParticle: "airdropCrate02",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_01sv: createAirdrop({
        button: {
            useImg: "map-airdrop-02.img",
            useParticle: "airdropCrate01",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01.img",
            residue: "none",
        },
        destroyType: "crate_10sv",
        explodeParticle: "airdropCrate02",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_02sv: createAirdrop({
        button: {
            useImg: "map-airdrop-02.img",
            useParticle: "airdropCrate01",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01.img",
            residue: "none",
        },
        destroyType: "crate_11sv",
        explodeParticle: "airdropCrate02",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_02de: createAirdrop({
        button: {
            useImg: "map-airdrop-02.img",
            useParticle: "airdropCrate01",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01.img",
            residue: "none",
        },
        destroyType: "crate_11de",
        explodeParticle: "airdropCrate02",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_02h: createAirdrop({
        collision: collider.createCircle(v2.create(0, 0), 2.5),
        button: {
            useImg: "map-airdrop-02h.img",
            useParticle: "airdropCrate01h",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01h.img",
            residue: "none",
        },
        destroyType: "cache_pumpkin_airdrop_02",
        explodeParticle: "airdropCrate02h",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_02tr: createAirdrop({
        button: {
            useImg: "map-airdrop-02.img",
            useParticle: "airdropCrate01",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01.img",
            residue: "none",
        },
        destroyType: "crate_11tr",
        explodeParticle: "airdropCrate02",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_01x: createAirdrop({
        button: {
            useImg: "map-airdrop-02x.img",
            useParticle: "airdropCrate01x",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01x.img",
            residue: "none",
        },
        destroyType: "crate_10",
        explodeParticle: "airdropCrate02x",
    } as unknown as Partial<ObstacleDef>),
    airdrop_crate_02x: createAirdrop({
        button: {
            useImg: "map-airdrop-02x.img",
            useParticle: "airdropCrate01x",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-airdrop-01x.img",
            residue: "none",
        },
        destroyType: "crate_11",
        explodeParticle: "airdropCrate02x",
    } as unknown as Partial<ObstacleDef>),
    class_shell_01: createAirdrop({
        collision: collider.createCircle(v2.create(0, 0), 2.25),
        button: {
            useImg: "map-class-shell-01b.img",
            useParticle: "classShell01a",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-class-shell-01a.img",
            residue: "none",
        },
        destroyType: "class_crate_common",
        smartLoot: true,
        explodeParticle: "classShell01b",
    } as unknown as Partial<ObstacleDef>),
    class_shell_02: createAirdrop({
        collision: collider.createCircle(v2.create(0, 0), 2.25),
        button: {
            useImg: "map-class-shell-02b.img",
            useParticle: "classShell02a",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-class-shell-02a.img",
            residue: "none",
        },
        destroyType: "class_crate_rare",
        smartLoot: true,
        explodeParticle: "classShell02b",
    } as unknown as Partial<ObstacleDef>),
    class_shell_03: createAirdrop({
        collision: collider.createCircle(v2.create(0, 0), 2.25),
        button: {
            useImg: "map-class-shell-03b.img",
            useParticle: "classShell03a",
            sound: { on: "airdrop_open_01", off: "" },
        },
        img: {
            sprite: "map-class-shell-03a.img",
            residue: "none",
            zIdx: 20,
        },
        destroyType: "class_crate_mythic",
        explodeParticle: "classShell03b",
    } as unknown as Partial<ObstacleDef>),
    class_crate_common_scout: createClassCrate({
        loot: [
            tierLoot("tier_guns_common_scout", 1, 1),
            autoLoot("crowbar_scout", 1),
            autoLoot("helmet01", 1),
            autoLoot("backpack01", 1),
            autoLoot("soda", 2),
        ],
        img: { sprite: "map-class-crate-scout.img" },
    }),
    class_crate_common_sniper: createClassCrate({
        loot: [
            tierLoot("tier_guns_common_sniper", 1, 1),
            autoLoot("kukri_sniper", 1),
            autoLoot("helmet01", 1),
            autoLoot("backpack01", 1),
            autoLoot("4xscope", 1),
        ],
        img: { sprite: "map-class-crate-sniper.img" },
    }),
    class_crate_common_healer: createClassCrate({
        loot: [
            tierLoot("tier_guns_common_healer", 1, 1),
            autoLoot("bonesaw_healer", 1),
            autoLoot("helmet01", 1),
            autoLoot("backpack01", 1),
            autoLoot("healthkit", 1),
            autoLoot("painkiller", 1),
            autoLoot("smoke", 3),
        ],
        img: { sprite: "map-class-crate-healer.img" },
    }),
    class_crate_common_demo: createClassCrate({
        loot: [
            tierLoot("tier_guns_common_demo", 1, 1),
            autoLoot("katana_demo", 1),
            autoLoot("helmet01", 1),
            autoLoot("chest01", 1),
            autoLoot("backpack02", 1),
            autoLoot("2xscope", 1),
            tierLoot("tier_throwables_demo", 3, 4),
        ],
        img: { sprite: "map-class-crate-demo.img" },
    }),
    class_crate_common_assault: createClassCrate({
        loot: [
            tierLoot("tier_guns_common_assault", 2, 2),
            autoLoot("spade_assault", 1),
            autoLoot("bandage", 5),
            autoLoot("helmet01", 1),
            autoLoot("chest01", 1),
            autoLoot("backpack01", 1),
        ],
        img: { sprite: "map-class-crate-assault.img" },
    }),
    class_crate_common_tank: createClassCrate({
        loot: [
            tierLoot("tier_guns_common_tank", 1, 1),
            autoLoot("warhammer_tank", 1),
            autoLoot("helmet02", 1),
            autoLoot("chest02", 1),
            autoLoot("backpack01", 1),
        ],
        img: { sprite: "map-class-crate-tank.img" },
    }),
    class_crate_common_classless: createClassCrate({
        loot: [
            tierLoot("tier_guns_common_classless", 1, 1),
            tierLoot("tier_medical", 1, 2),
            tierLoot("tier_throwables", 1, 2),
            tierLoot("tier_ammo", 1, 1),
            autoLoot("naginata_daemon", 1),
        ],
        img: { sprite: "map-class-crate-classless.img" },
    }),
    class_crate_rare_scout: createClassCrate({
        loot: [
            tierLoot("tier_guns_rare_scout", 1, 1),
            autoLoot("crowbar_scout", 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 1, 1),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 2, 2),
            tierLoot("tier_airdrop_throwables", 1, 1),
        ],
        img: { sprite: "map-class-crate-scout.img" },
    }),
    class_crate_rare_sniper: createClassCrate({
        loot: [
            tierLoot("tier_guns_rare_sniper", 1, 1),
            autoLoot("kukri_sniper", 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 1, 1),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 2, 2),
            tierLoot("tier_airdrop_throwables", 1, 1),
        ],
        img: { sprite: "map-class-crate-sniper.img" },
    }),
    class_crate_rare_healer: createClassCrate({
        loot: [
            tierLoot("tier_guns_rare_healer", 1, 1),
            autoLoot("bonesaw_healer", 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 1, 1),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 2, 2),
            tierLoot("tier_airdrop_throwables", 1, 1),
        ],
        img: { sprite: "map-class-crate-healer.img" },
    }),
    class_crate_rare_demo: createClassCrate({
        loot: [
            tierLoot("tier_guns_rare_demo", 1, 1),
            autoLoot("katana_demo", 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 1, 1),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 2, 2),
            tierLoot("tier_throwables_demo", 4, 5),
        ],
        img: { sprite: "map-class-crate-demo.img" },
    }),
    class_crate_rare_assault: createClassCrate({
        loot: [
            tierLoot("tier_guns_rare_assault", 2, 2),
            autoLoot("spade_assault", 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 1, 1),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 2, 2),
            tierLoot("tier_airdrop_throwables", 1, 1),
        ],
        img: { sprite: "map-class-crate-assault.img" },
    }),
    class_crate_rare_tank: createClassCrate({
        loot: [
            tierLoot("tier_guns_rare_tank", 1, 1),
            autoLoot("warhammer_tank", 1),
            tierLoot("tier_airdrop_armor", 1, 1),
            tierLoot("tier_medical", 1, 1),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 2, 2),
            tierLoot("tier_airdrop_throwables", 1, 1),
        ],
        img: { sprite: "map-class-crate-tank.img" },
    }),
    class_crate_rare_classless: createClassCrate({
        loot: [
            tierLoot("tier_guns_rare_classless", 1, 1),
            autoLoot("naginata_daemon", 1),
            autoLoot("chest03", 1),
            tierLoot("tier_medical", 2, 3),
            tierLoot("tier_airdrop_throwables", 2, 2),
            tierLoot("tier_airdrop_scopes", 1, 1),
            tierLoot("tier_airdrop_ammo", 2, 2),
        ],
        img: { sprite: "map-class-crate-classless.img" },
    }),
    class_crate_mythic: createClassCrate({
        loot: [tierLoot("tier_class_crate_mythic", 1, 1)],
        img: { sprite: "map-class-crate-03.img" },
    }),
    mil_crate_01: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.7, 1.25)),
        health: 100,
        loot: [tierLoot("tier_knives", 1, 1)],
        map: { display: false },
        terrain: { grass: true, beach: true },
        img: { sprite: "map-crate-mil-01.img" },
        sound: { explode: "crate_break_01" },
    }),
    mil_crate_02: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.7, 1.25)),
        health: 100,
        loot: [
            autoLoot("ot38", 1),
            autoLoot("ot38", 1),
            autoLoot("ot38", 1),
            autoLoot("ot38", 1),
        ],
        map: { display: false },
        terrain: { grass: true, beach: true },
        img: { sprite: "map-crate-mil-02.img" },
        sound: { explode: "crate_break_01" },
    }),
    mil_crate_03: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.7, 1.25)),
        health: 100,
        loot: [autoLoot("ots38_dual", 1), autoLoot("outfitSpetsnaz", 1)],
        map: { display: false },
        terrain: { grass: true, beach: true },
        img: { sprite: "map-crate-mil-03.img" },
        sound: { explode: "crate_break_01" },
    }),
    mil_crate_04: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.7, 1.25)),
        health: 100,
        loot: [tierLoot("tier_guns", 1, 1), tierLoot("tier_throwables", 2, 3)],
        map: { display: false },
        terrain: { grass: true, beach: true },
        img: { sprite: "map-crate-mil-04.img" },
        sound: { explode: "crate_break_01" },
    }),
    mil_crate_05: createCrate({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.7, 1.25)),
        health: 100,
        loot: [tierLoot("tier_guns", 1, 2), tierLoot("tier_snipers", 1, 2)],
        map: { display: true, color: 0x374626 },
        terrain: { grass: true, beach: true },
        img: { sprite: "map-crate-mil-05.img" },
        sound: { explode: "crate_break_01" },
    }),
} as const satisfies Record<string, MapObjectDef>;

export const Crates = CrateDefs;
