import { collider } from "../../../utils/collider";
import { util } from "../../../utils/util";
import { v2 } from "../../../utils/v2";
import type {
    MapObjectDef,
    ObstacleDef,
} from "../../mapObjectsTyping";
import { tierLoot, autoLoot } from "../mapObjectHelpers"

//
// Lootable and non-lootable furniture obstacles
//

function createWoodBarrel<T extends ObstacleDef>(params: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "barrel",
        scale: { createMin: 1, createMax: 1, destroy: 0.8 },
        collision: collider.createCircle(v2.create(0, 0), 1.75),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 20,
        hitParticle: "outhouseChip",
        explodeParticle: "barrelPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: true, color: 0xab6f22, scale: 1 },
        terrain: { grass: true, beach: true },
        img: {
            sprite: "map-barrel-02.img",
            residue: "map-barrel-res-02.img",
            scale: 0.4,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_crate_bullet",
            punch: "wood_crate_bullet",
            explode: "barrel_break_02",
            enter: "none",
        },
    };
    return util.mergeDeep(t, params || {});
}
function createBed<T extends ObstacleDef>(params: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "furniture",
        scale: { createMin: 1, createMax: 1, destroy: 0.9 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.8, 3.4)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 100,
        hitParticle: "clothHit",
        explodeParticle: ["woodPlank", "clothBreak"],
        reflectBullets: false,
        loot: [],
        map: { display: true, color: 0x663300, scale: 0.875 },
        terrain: { grass: true, beach: true },
        img: {
            sprite: "map-bed-02.img",
            residue: "map-bed-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "cloth_bullet",
            punch: "cloth_punch",
            explode: "cloth_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, params || {});
}
function createBookShelf<T extends ObstacleDef>(params: Partial<T>): T {
    const ObstacleDef = {
        type: "obstacle",
        obstacleType: "furniture",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3.5, 1)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 75,
        hitParticle: "woodChip",
        explodeParticle: ["woodPlank", "book"],
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-bookshelf-01.img",
            residue: "map-drawers-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_prop_bullet",
            punch: "wood_prop_bullet",
            explode: "drawers_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(ObstacleDef, params || {});
}
function createControlPanel<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        scale: { createMin: 1, createMax: 1, destroy: 0.8 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1, 1)),
        height: 0.5,
        collidable: true,
        destructible: true,
        explosion: "explosion_barrel",
        health: 250,
        hitParticle: "barrelChip",
        explodeParticle: "depositBoxGreyBreak",
        reflectBullets: true,
        loot: [],
        map: { display: false },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-power-box-01.img",
            residue: "",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wall_bullet",
            punch: "metal_punch",
            explode: "deposit_box_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createCouch<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "furniture",
        scale: { createMin: 1, createMax: 1, destroy: 0.85 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4.5, 1.5)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 125,
        hitParticle: "clothHit",
        explodeParticle: ["woodPlank", "clothBreak"],
        reflectBullets: false,
        loot: [],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-couch-01.img",
            residue: "map-couch-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "cloth_bullet",
            punch: "cloth_punch",
            explode: "cloth_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createDepositBox<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "locker",
        scale: { createMin: 1, createMax: 1, destroy: 1 },
        collision: collider.createAabbExtents(v2.create(0, 0.15), v2.create(2.5, 1)),
        height: 10,
        collidable: true,
        destructible: true,
        health: 20,
        hitParticle: "barrelChip",
        explodeParticle: "depositBoxGreyBreak",
        reflectBullets: true,
        loot: [tierLoot("tier_world", 1, 1)],
        lootSpawn: { offset: v2.create(0, -1), speedMult: 0 },
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-deposit-box-01.img",
            residue: "none",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wall_bullet",
            punch: "metal_punch",
            explode: "deposit_box_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createDrawer<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "furniture",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0.15), v2.create(2.5, 1.25)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 75,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_container", 1, 1)],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-drawers-01.img",
            residue: "map-drawers-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_prop_bullet",
            punch: "wood_prop_bullet",
            explode: "drawers_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createGunMount<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "furniture",
        scale: { createMin: 1, createMax: 1, destroy: 0.9 },
        collision: collider.createAabbExtents(v2.create(0, 0.2), v2.create(2.25, 0.7)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 50,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        lootSpawn: { offset: v2.create(0, -1), speedMult: 0 },
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-gun-mount-01.img",
            residue: "map-drawers-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_prop_bullet",
            punch: "wood_prop_bullet",
            explode: "barrel_break_02",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createLocker<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "locker",
        scale: { createMin: 1, createMax: 1, destroy: 1 },
        collision: collider.createAabbExtents(v2.create(0, 0.15), v2.create(1.5, 0.6)),
        height: 10,
        collidable: true,
        destructible: true,
        health: 20,
        hitParticle: "barrelChip",
        explodeParticle: "lockerBreak",
        reflectBullets: true,
        loot: [tierLoot("tier_world", 1, 1)],
        lootSpawn: { offset: v2.create(0, -1), speedMult: 0 },
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-locker-01.img",
            residue: "",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wall_bullet",
            punch: "metal_punch",
            explode: "deposit_box_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createOven<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "furniture",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0.15), v2.create(1.7, 1.3)),
        height: 0.5,
        collidable: true,
        destructible: true,
        explosion: "explosion_barrel",
        health: 200,
        hitParticle: "barrelChip",
        explodeParticle: "barrelBreak",
        reflectBullets: true,
        loot: [],
        map: { display: false, color: 0xe3e3e3, scale: 0.875 },
        terrain: { grass: true, beach: true },
        img: {
            sprite: "map-oven-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "barrel_bullet",
            punch: "barrel_bullet",
            explode: "oven_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createPlanter<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "pot",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.25, 4.25)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 100,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: true, color: 0x663300, scale: 0.875 },
        terrain: { grass: true, beach: true, riverShore: true },
        img: {
            sprite: "map-planter-01.img",
            residue: "map-planter-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "toilet_porc_bullet",
            punch: "toilet_porc_bullet",
            explode: "ceramic_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createBottle<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "pot",
        scale: { createMin: 1, createMax: 1, destroy: 0.8 },
        collision: collider.createCircle(v2.create(0, 0), 1.5),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 50,
        hitParticle: "potChip",
        explodeParticle: "potBreak",
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: true, color: 0x663300, scale: 1 },
        terrain: { grass: true, beach: true },
        img: {
            sprite: "map-pot-01.img",
            residue: "map-pot-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "toilet_porc_bullet",
            punch: "toilet_porc_bullet",
            explode: "toilet_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createRefrigerator<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0.15), v2.create(1.7, 1.25)),
        height: 0.5,
        collidable: true,
        destructible: false,
        health: 100,
        hitParticle: "redChip",
        explodeParticle: "woodPlank",
        reflectBullets: true,
        loot: [],
        map: { display: false, color: 0x76000b, scale: 0.875 },
        terrain: { grass: true, beach: true },
        img: {
            sprite: "map-refrigerator-01.img",
            residue: "map-crate-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wall_bullet",
            punch: "metal_punch",
            explode: "barrel_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createSafe<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        scale: { createMin: 0.8, createMax: 0.8, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0.1), v2.create(1.25, 1.25)),
        height: 0.5,
        collidable: true,
        destructible: true,
        stonePlated: true,
        health: 400,
        reflectBullets: false,
        hitParticle: "rockEyeChip",
        explodeParticle: "rockEyeBreak",
        loot: [tierLoot("tier_safe_throwables", 1, 1), tierLoot("tier_safe", 1, 1)],
        map: { display: true, color: 0x171412, scale: 1 },
        terrain: { grass: true, beach: false, riverShore: true },
        img: {
            sprite: "map-safe-01.img",
            residue: "map-stone-res-04.img",
            scale: 0.4,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "stone_bullet",
            punch: "stone_bullet",
            explode: "stone_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createSink<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        scale: { createMin: 1, createMax: 1, destroy: 0.8 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2, 1.5)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 100,
        reflectBullets: false,
        hitParticle: "whiteChip",
        explodeParticle: "toiletBreak",
        loot: [
            tierLoot("tier_toilet", 2, 2),
        ],
        map: { display: false, color: 0xb3b3b3, scale: 1 },
        img: {
            sprite: "map-sink-01.img",
            residue: "map-sink-res-01.img",
            scale: 0.35,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "toilet_porc_bullet",
            punch: "toilet_porc_bullet",
            explode: "toilet_break_01",
            enter: "none",
        },
        terrain: { grass: true, beach: false },
    };
    return util.mergeDeep(t, e || {});
}
function createTable<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "furniture",
        scale: { createMin: 1, createMax: 1, destroy: 0.75 },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(2.5, 2)),
        height: 0.5,
        collidable: false,
        destructible: true,
        health: 100,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: true, beach: true },
        img: {
            sprite: "map-table-01.img",
            residue: "map-table-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 60,
        },
        sound: {
            bullet: "wood_prop_bullet",
            punch: "wood_prop_bullet",
            explode: "crate_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}
function createToilet<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        obstacleType: "toilet",
        scale: { createMin: 1, createMax: 1, destroy: 0.8 },
        collision: collider.createCircle(v2.create(0, 0.25), 1.18),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 100,
        reflectBullets: false,
        hitParticle: "whiteChip",
        explodeParticle: "toiletBreak",
        loot: [tierLoot("tier_toilet", 2, 3)],
        map: { display: false, color: 0xb3b3b3, scale: 1 },
        img: {
            sprite: "map-toilet-01.img",
            residue: "map-toilet-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "toilet_porc_bullet",
            punch: "toilet_porc_bullet",
            explode: "toilet_break_01",
            enter: "none",
        },
        terrain: { grass: true, beach: false },
    };
    return util.mergeDeep(t, e || {});
}
function createWheel<T extends ObstacleDef>(e: Partial<T>): T {
    const t = {
        type: "obstacle",
        scale: { createMin: 1, createMax: 1, destroy: 1 },
        collision: collider.createCircle(v2.create(0, 2.3), 4.6),
        height: 10,
        collidable: true,
        destructible: false,
        health: 300,
        hitParticle: "barrelChip",
        explodeParticle: "barrelBreak",
        reflectBullets: true,
        loot: [],
        map: { display: false, color: 0x604a40, scale: 1 },
        terrain: { grass: true, beach: false },
        img: {
            sprite: "map-wheel-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "silo_bullet",
            punch: "silo_bullet",
            explode: "barrel_break_01",
            enter: "none",
        },
    };
    return util.mergeDeep(t, e || {});
}

const FurnitureDefs = {
    barrel_02: createWoodBarrel({ health: 60 }),
    barrel_03: createWoodBarrel({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.25, 0.5)),
        health: 20,
        img: {
            sprite: "map-barrel-03.img",
            residue: "map-barrel-res-03.img",
            scale: 0.45,
        },
    }),
    barrel_04: createWoodBarrel({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.25, 0.5)),
        health: 20,
        loot: [tierLoot("tier_soviet", 2, 3)],
        img: {
            sprite: "map-barrel-04.img",
            residue: "map-barrel-res-03.img",
            scale: 0.45,
        },
    }),
    barrel_05: createWoodBarrel({
        // coconut barrel
        health: 80,
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-barrel-05.img",
        },
        loot: [
            tierLoot("tier_surviv", 0, 2),
            tierLoot("tier_coconut_outfit", 1, 1),
            autoLoot("coconut", 4),
        ],
    }),
    bathhouse_rocks_01: createControlPanel({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.55, 1.55)),
        destructible: false,
        img: { sprite: "map-bathrocks-01.img" },
    }),
    bed_sm_01: createBed({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.4, 3.4)),
        img: { sprite: "map-bed-01.img" },
    }),
    bed_lg_01: createBed({
        img: { residue: "map-bed-res-02.img" },
    }),
    bookshelf_01: createBookShelf({
        img: { sprite: "map-bookshelf-01.img" },
        loot: [tierLoot("tier_world", 1, 1)],
    }),
    bookshelf_02: createBookShelf({
        img: { sprite: "map-bookshelf-02.img" },
        loot: [tierLoot("tier_soviet", 2, 3)],
    }),
    chair_01: createCouch({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1, 1.25)),
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        img: {
            sprite: "map-chair-01.img",
            residue: "map-drawers-res.img",
        },
        sound: {
            bullet: "wood_prop_bullet",
            punch: "wood_prop_bullet",
            explode: "crate_break_01",
            enter: "none",
        },
    }),
    chair_02: createCouch({
        collision: collider.createCircle(v2.create(0, 0), 1.25),
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        img: {
            sprite: "map-chair-02.img",
            residue: "map-drawers-res.img",
        },
        sound: {
            bullet: "wood_prop_bullet",
            punch: "wood_prop_bullet",
            explode: "crate_break_01",
            enter: "none",
        },
    }),
    couch_01: createCouch({}),
    couch_02: createCouch({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3, 1.5)),
        img: { sprite: "map-couch-02.img" },
    }),
    couch_02b: createCouch({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3, 1.5)),
        img: { sprite: "map-couch-02.img", mirrorY: true },
    }),
    couch_03: createCouch({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.5, 1.5)),
        img: { sprite: "map-couch-03.img" },
    }),
    bottle_01: createBottle({
        collision: collider.createCircle(v2.create(0, 0), 0.5),
        health: 12,
        hitParticle: "bottleBrownChip",
        explodeParticle: "bottleBrownBreak",
        img: {
            sprite: "map-bottle-01.img",
            residue: "none",
        },
        loot: [],
        sound: {
            bullet: "glass_bullet",
            punch: "glass_bullet",
            explode: "window_break_01",
            enter: "none",
        },
    }),
    bottle_02: createBottle({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(0.5, 0.5)),
        health: 20,
        hitParticle: "bottleBlueChip",
        explodeParticle: "bottleBlueBreak",
        img: {
            sprite: "map-bottle-02.img",
            residue: "none",
        },
        loot: [],
        sound: {
            bullet: "glass_bullet",
            punch: "glass_bullet",
            explode: "window_break_01",
            enter: "none",
        },
    }),
    bottle_04: createBottle({
        collision: collider.createCircle(v2.create(0, 0), 0.5),
        health: 20,
        hitParticle: "bottleWhiteChip",
        explodeParticle: "bottleWhiteBreak",
        img: {
            sprite: "map-bottle-04.img",
            residue: "none",
        },
        loot: [],
        sound: {
            bullet: "glass_bullet",
            punch: "glass_bullet",
            explode: "window_break_01",
            enter: "none",
        },
    }),
    bottle_05: createBottle({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(0.5, 0.5)),
        health: 20,
        hitParticle: "bottleWhiteChip",
        explodeParticle: "bottleWhiteBreak",
        img: {
            sprite: "map-bottle-05.img",
            residue: "none",
        },
        loot: [],
        sound: {
            bullet: "glass_bullet",
            punch: "glass_bullet",
            explode: "window_break_01",
            enter: "none",
        },
    }),
    candle_01: {
        type: "obstacle",
        map: { display: false, color: 0xffffff, scale: 1 },
        scale: { createMin: 1, createMax: 1, destroy: 0.5 },
        collision: collider.createCircle(v2.create(0, 0), 0.5),
        height: 0.5,
        collidable: false,
        destructible: false,
        health: 150,
        hitParticle: "goldChip",
        explodeParticle: "barrelBreak",
        reflectBullets: false,
        loot: [],
        img: {
            sprite: "map-candle-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "none",
            punch: "none",
            explode: "none",
            enter: "none",
        },
    },
    deposit_box_01: createDepositBox({
        img: { sprite: "map-deposit-box-01.img" },
        loot: [tierLoot("tier_world", 1, 1)],
    }),
    deposit_box_02: createDepositBox({
        explodeParticle: "depositBoxGoldBreak",
        img: { sprite: "map-deposit-box-02.img" },
        loot: [tierLoot("tier_soviet", 1, 2), tierLoot("tier_guns", 1, 1)],
    }),
    deposit_box_03: createDepositBox({
        explodeParticle: "depositBoxSilverBreak",
        img: { sprite: "map-deposit-box-03.img" },
        loot: [
            tierLoot("tier_chest", 1, 1),
            tierLoot("tier_guns", 1, 2),
            tierLoot("tier_surviv", 1, 2),
        ],
    }),
    drawers_01: createDrawer({
        img: { sprite: "map-drawers-01.img" },
        loot: [tierLoot("tier_container", 1, 1)],
    }),
    drawers_02: createDrawer({
        img: { sprite: "map-drawers-02.img" },
        loot: [tierLoot("tier_soviet", 2, 3)],
    }),
    fire_ext_01: {
        type: "obstacle",
        scale: { createMin: 1, createMax: 1, destroy: 0.8 },
        collision: collider.createCircle(v2.create(0.35, 0), 1),
        height: 0.5,
        collidable: true,
        destructible: true,
        createSmoke: true,
        health: 75,
        hitParticle: "redChip",
        explodeParticle: "redBreak",
        reflectBullets: true,
        loot: [],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-fire-ext-01.img",
            residue: "map-fire-ext-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "barrel_bullet",
            punch: "barrel_bullet",
            explode: "explosion_smoke_01",
            enter: "none",
        },
    },
    grill_01: createOven({
        collision: collider.createCircle(v2.create(0, 0), 1.55),
        img: { sprite: "map-grill-01.img" },
    }),
    gun_mount_empty: createGunMount({
        loot: [],
        img: { sprite: "map-gun-mount-empty.img" },
    }),
    gun_mount_01: createGunMount({
        loot: [autoLoot("m870", 1)],
        img: { sprite: "map-gun-mount-01.img" },
    }),
    gun_mount_02: createGunMount({
        loot: [autoLoot("mp220", 1)],
        img: { sprite: "map-gun-mount-02.img" },
    }),
    gun_mount_03: createGunMount({
        loot: [autoLoot("qbb97", 1)],
        img: { sprite: "map-gun-mount-03.img" },
    }),
    gun_mount_04: createGunMount({
        loot: [autoLoot("woodaxe_bloody", 1)],
        img: { sprite: "map-gun-mount-04.img" },
    }),
    gun_mount_05: createGunMount({
        loot: [autoLoot("m1100", 1)],
        img: { sprite: "map-gun-mount-05.img" },
    }),
    gun_mount_06: createGunMount({
        loot: [autoLoot("cutlass_gold", 1)],
        img: { sprite: "map-gun-mount-06.img" },
    }),
    gun_mount_07: createGunMount({
        loot: [autoLoot("spas16", 1)],
        img: { sprite: "map-gun-mount-07.img" },
    }),
    locker_01: createLocker({
        img: { sprite: "map-locker-01.img" },
        loot: [tierLoot("tier_world", 1, 1)],
    }),
    locker_02: createLocker({
        img: { sprite: "map-locker-02.img" },
        loot: [tierLoot("tier_police", 1, 1)],
    }),
    locker_03: createLocker({
        img: { sprite: "map-locker-03.img" },
        loot: [
            autoLoot("ak47", 1),
            autoLoot("backpack02", 1),
            tierLoot("tier_khaki_outfit", 1, 1),
        ],
    }),
    oven_01: createOven({}),
    piano_01: {
        type: "obstacle",
        scale: {
            createMin: 1,
            createMax: 1,
            destroy: 0.75,
        },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3.75, 1)),
        height: 0.5,
        collidable: true,
        destructible: false,
        health: 75,
        hitParticle: "woodChip",
        explodeParticle: ["woodPlank", "book"],
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-piano-01.img",
            residue: "map-drawers-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "piano_hit",
            punch: "piano_hit",
            explode: "drawers_break_01",
            enter: "none",
        },
    },
    planter_01: createPlanter({}),
    planter_02: createPlanter({
        img: { sprite: "map-planter-02.img" },
    }),
    planter_03: createPlanter({
        img: { sprite: "map-planter-03.img" },
    }),
    planter_04: createPlanter({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.5, 1.5)),
        img: { sprite: "map-planter-04.img" },
        destructible: false,
        button: {
            interactionRad: 0.1,
            interactionText: "game-use",
            useOnce: true,
            useType: "",
            useDelay: 0.25,
            useDir: v2.create(1, 0),
            useImg: "map-planter-05.img",
            sound: {
                on: "watering_01",
                off: "watering_01",
            },
        },
    }),
    planter_06: createPlanter({
        img: {
            sprite: "map-planter-06.img",
            residue: "map-planter-res-02.img",
        },
    }),
    planter_07: createPlanter({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(1.5, 1.5)),
        img: {
            sprite: "map-planter-07.img",
            residue: "map-planter-res-03.img",
        },
        destructible: true,
    }),
    pot_01: createBottle({}),
    pot_02: createBottle({
        img: { sprite: "map-pot-02.img" },
        loot: [autoLoot("spas12", 1)],
    }),
    pot_03: createBottle({ img: { sprite: "map-pot-03.img" } }),
    pot_03b: createBottle({
        img: { sprite: "map-pot-03.img" },
        loot: [autoLoot("outfitWoodsCloak", 1), autoLoot("backpack03", 1)],
    }),
    pot_03c: createBottle({
        img: { sprite: "map-pot-03.img" },
        loot: [tierLoot("tier_pavilion", 1, 1)],
    }),
    pot_04: createBottle({ img: { sprite: "map-pot-04.img" } }),
    pot_05: createBottle({
        img: { sprite: "map-pot-05.img" },
        loot: [autoLoot("scout_elite", 1), tierLoot("tier_islander_outfit", 1, 1)],
    }),
    rack_01: createDrawer({
        collision: collider.createAabbExtents(v2.create(0, 0.2), v2.create(2, 1.25)),
        scale: { createMin: 1, createMax: 1, destroy: 0.9 },
        img: {
            sprite: "map-rack-01.img",
            residue: "map-rack-res-01.img",
        },
        hitParticle: "woodChip",
        explodeParticle: ["potBreak", "woodPlank"],
        loot: [
            tierLoot("tier_revolvers", 0, 1),
            tierLoot("tier_medical", 1, 1),
            tierLoot("tier_vending_soda", 1, 2),
        ],
        sound: { explode: "window_break_02" },
    }),
    refrigerator_01: createRefrigerator({}),
    refrigerator_01b: createRefrigerator({
        scale: { createMin: 1, createMax: 1, destroy: 1 },
        health: 250,
    }),
    safe_01: createSafe({}),
    screen_01: {
        type: "obstacle",
        obstacleType: "furniture",
        scale: {
            createMin: 1,
            createMax: 1,
            destroy: 0.85,
        },
        collision: collider.createAabbExtents(v2.create(0, 0.05), v2.create(4, 0.2)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 25,
        hitParticle: "clothHit",
        explodeParticle: "barrelBreak",
        reflectBullets: false,
        loot: [],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-screen-01.img",
            residue: "map-screen-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "cloth_bullet",
            punch: "cloth_punch",
            explode: "screen_break_01",
            enter: "none",
        },
    },
    sink_01: createSink({}),
    stand_01: {
        type: "obstacle",
        obstacleType: "furniture",
        scale: {
            createMin: 1,
            createMax: 1,
            destroy: 0.75,
        },
        collision: collider.createAabbExtents(v2.create(0, 0.15), v2.create(1.25, 1.25)),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 75,
        hitParticle: "woodChip",
        explodeParticle: "woodPlank",
        reflectBullets: false,
        loot: [tierLoot("tier_world", 1, 1)],
        map: { display: false, color: 0x663300, scale: 0.875 },
        terrain: { grass: false, beach: true },
        img: {
            sprite: "map-stand-01.img",
            residue: "map-drawers-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "wood_prop_bullet",
            punch: "wood_prop_bullet",
            explode: "drawers_break_01",
            enter: "none",
        },
    },
    power_box_01: createControlPanel({}),
    stove_01: createControlPanel({
        obstacleType: "furniture",
        scale: {
            createMin: 1,
            createMax: 1,
            destroy: 0.85,
        },
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3, 2.25)),
        disableBuildingOccupied: true,
        damageCeiling: true,
        explosion: "explosion_stove",
        height: 10,
        health: 500,
        img: { sprite: "map-stove-01.img" },
        sound: {
            bullet: "wall_bullet",
            punch: "metal_punch",
            explode: "oven_break_01",
            enter: "none",
        },
    }),
    stove_02: createControlPanel({
        obstacleType: "furniture",
        collision: collider.createCircle(v2.create(0, 0), 1.5),
        disableBuildingOccupied: true,
        damageCeiling: true,
        explosion: "explosion_stove",
        height: 10,
        health: 400,
        img: { sprite: "map-stove-02.img" },
        sound: {
            bullet: "wall_bullet",
            punch: "metal_punch",
            explode: "oven_break_01",
            enter: "none",
        },
    }),
    table_01: createTable({}),
    table_01x: createTable({ img: { sprite: "map-table-01x.img" } }),
    table_01d: createTable({
        collision: collider.createAabbExtents(v2.create(0, -0.5), v2.create(2.5, 2)),
        img: { sprite: "map-table-01d.img" },
    }),
    table_02: createTable({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4.5, 2.5)),
        health: 125,
        img: {
            sprite: "map-table-02.img",
            residue: "map-table-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 60,
        },
    }),
    table_02x: createTable({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4.5, 2.5)),
        health: 125,
        img: {
            sprite: "map-table-02x.img",
            residue: "map-table-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 60,
        },
    }),
    table_03: createTable({
        collision: collider.createCircle(v2.create(0, 0), 2.5),
        health: 125,
        img: {
            sprite: "map-table-03.img",
            residue: "map-table-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 60,
        },
    }),
    table_03x: createTable({
        collision: collider.createCircle(v2.create(0, 0), 2.5),
        health: 125,
        img: {
            sprite: "map-table-03x.img",
            residue: "map-table-res-01.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 60,
        },
    }),
    table_04: createTable({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(4.5, 2)),
        health: 225,
        img: {
            sprite: "map-table-04.img",
            residue: "map-table-res-02.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 60,
        },
    }),
    table_05: createTable({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(9, 2.75)),
        health: 300,
        scale: { createMin: 1, createMax: 1, destroy: 0.95 },
        img: {
            sprite: "map-table-05.img",
            residue: "map-table-res-03.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 60,
        },
    }),
    toilet_01: createToilet({
        img: { sprite: "map-toilet-01.img" },
        loot: [tierLoot("tier_toilet", 2, 3)],
    }),
    toilet_02: createToilet({
        img: { sprite: "map-toilet-02.img" },
        loot: [tierLoot("tier_soviet", 3, 4)],
    }),
    toilet_02b: createToilet({
        img: {
            sprite: "map-toilet-02.img",
            tint: 0xb4b4b4,
        },
        loot: [autoLoot("fireaxe", 1)],
    }),
    toilet_03: createToilet({
        reflectBullets: true,
        hitParticle: "barrelChip",
        explodeParticle: "toiletMetalBreak",
        img: {
            sprite: "map-toilet-03.img",
            residue: "map-toilet-res-02.img",
        },
        loot: [tierLoot("tier_world", 1, 2)],
        sound: {
            bullet: "toilet_metal_bullet",
            punch: "toilet_metal_bullet",
            explode: "toilet_break_02",
        },
    }),
    toilet_04: createToilet({
        reflectBullets: true,
        hitParticle: "barrelChip",
        explodeParticle: "toiletMetalBreak",
        img: {
            sprite: "map-toilet-04.img",
            residue: "map-toilet-res-02.img",
        },
        loot: [tierLoot("tier_soviet", 2, 3)],
        sound: {
            bullet: "toilet_metal_bullet",
            punch: "toilet_metal_bullet",
            explode: "toilet_break_02",
        },
    }),
    toilet_05: createToilet({
        scale: { createMin: 1, createMax: 1, destroy: 0.9 },
        collision: collider.createCircle(v2.create(0, 0.25), 1.56),
        reflectBullets: true,
        img: {
            sprite: "map-toilet-05.img",
            residue: "map-toilet-res-03.img",
            scale: 0.66,
        },
        hitParticle: "toiletGoldChip",
        explodeParticle: "toiletGoldBreak",
        loot: [
            tierLoot("tier_toilet_gold", 1, 1),
            tierLoot("tier_medical", 3, 4),
            autoLoot("coconut", 5),
            autoLoot("outfitGold", 1),
        ],
        sound: {
            bullet: "toilet_metal_bullet",
            punch: "toilet_metal_bullet",
            explode: "toilet_break_02",
        },
    }),
    towelrack_01: createBookShelf({
        collision: collider.createAabbExtents(v2.create(0, 0), v2.create(3, 1)),
        img: { sprite: "map-towelrack-01.img" },
        explodeParticle: ["woodPlank", "clothBreak"],
    }),
    vat_01: {
        type: "obstacle",
        scale: { createMin: 1, createMax: 1, destroy: 0.9 },
        collision: collider.createCircle(v2.create(0, 0), 2),
        height: 0.5,
        collidable: true,
        destructible: true,
        health: 250,
        reflectBullets: false,
        hitParticle: "glassChip",
        explodeParticle: "windowBreak",
        loot: [],
        map: { display: true, color: 0xb3b3b3, scale: 1 },
        terrain: { grass: false, beach: false },
        img: {
            sprite: "map-vat-01.img",
            residue: "map-vat-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "glass_bullet",
            punch: "glass_bullet",
            explode: "window_break_01",
            enter: "none",
        },
    },
    vat_02: {
        type: "obstacle",
        scale: {
            createMin: 1,
            createMax: 1,
            destroy: 0.95,
        },
        collision: collider.createCircle(v2.create(0, 0), 3.1),
        height: 0.5,
        collidable: true,
        destructible: false,
        health: 1e3,
        reflectBullets: false,
        hitParticle: "glassChip",
        explodeParticle: "windowBreak",
        loot: [],
        map: { display: true, color: 0xb3b3b3, scale: 1 },
        terrain: { grass: true, beach: false },
        img: {
            sprite: "map-vat-02.img",
            residue: "map-vat-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 10,
        },
        sound: {
            bullet: "glass_bullet",
            punch: "glass_bullet",
            explode: "window_break_01",
            enter: "none",
        },
    },
    vat_03: {
        type: "obstacle",
        scale: { createMin: 1, createMax: 1, destroy: 0.9 },
        collision: collider.createCircle(v2.create(0, 0), 1.75),
        height: 0.2,
        collidable: false,
        destructible: false,
        health: 250,
        reflectBullets: false,
        hitParticle: "glassChip",
        explodeParticle: "windowBreak",
        loot: [],
        map: { display: true, color: 0xb3b3b3, scale: 1 },
        terrain: { grass: false, beach: false },
        img: {
            sprite: "map-vat-03.img",
            residue: "map-vat-res.img",
            scale: 0.5,
            alpha: 1,
            tint: 0xffffff,
            zIdx: 50,
        },
        sound: {
            bullet: "glass_bullet",
            punch: "glass_bullet",
            explode: "window_break_01",
            enter: "none",
        },
        button: {
            interactionRad: 1.75,
            interactionText: "game-use",
            useOnce: true,
            destroyOnUse: true,
            isVat: true,
            roleToPromote: "classless",
            useDelay: 0.1,
            useDir: v2.create(-1, 0),
            useImg: "",
            sound: {
                on: "",
                off: "",
            },
        },
    },
    vending_01: (function () {
        const t = {
            type: "obstacle",
            obstacleType: "vending",
            scale: {
                createMin: 1,
                createMax: 1,
                destroy: 0.75,
            },
            collision: collider.createAabbExtents(
                v2.create(0, 0.15),
                v2.create(1.7, 1.25),
            ),
            height: 0.5,
            collidable: true,
            destructible: true,
            health: 150,
            hitParticle: "blueChip",
            explodeParticle: ["windowBreak", "lockerBreak"],
            reflectBullets: true,
            loot: [tierLoot("tier_vending_soda", 1, 3), autoLoot("soda", 1)],
            map: {
                display: false,
                color: 0x2aad,
                scale: 0.875,
            },
            terrain: { grass: true, beach: true },
            img: {
                sprite: "map-vending-soda-01.img",
                residue: "map-vending-res.img",
                scale: 0.5,
                alpha: 1,
                tint: 0xffffff,
                zIdx: 10,
            },
            sound: {
                bullet: "wall_bullet",
                punch: "metal_punch",
                explode: "vending_break_01",
                enter: "none",
            },
        };
        return util.mergeDeep(t, {});
    })(),
    wheel_01: createWheel({
        button: {
            interactionRad: 1,
            interactionText: "game-use",
            useOnce: true,
            useType: "",
            useDelay: 2.5,
            useDir: v2.create(-1, 0),
            useImg: "map-wheel-02.img",
            sound: { on: "wheel_control_01", off: "" },
        },
    }),
    wheel_02: createWheel({ img: { sprite: "map-wheel-02.img" } }),
    wheel_03: createWheel({ img: { sprite: "map-wheel-03.img" } }),
} as const satisfies Record<string, MapObjectDef>;

export const Furniture = FurnitureDefs