import { Rarity } from "../../gameConfig.ts";

export enum EmoteCategory {
    Locked,
    Faces,
    Food,
    Animals,
    Logos,
    Other,
    Flags,
    Default,
}

export interface EmoteDef {
    readonly type: "emote";
    name?: string;
    rarity?: Rarity;
    texture: string;
    sound: string;
    channel: string;
    teamOnly?: boolean;
    category: number;
    noCustom?: boolean;
}

export const EmotesDefs: Record<string, EmoteDef> = {
        // special emotes
    emote_medical: {
        type: "emote",
        texture: "emote-medical-healthkit.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo: {
        type: "emote",
        texture: "ammo-box.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo9mm: {
        type: "emote",
        texture: "ammo-9mm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo12gauge: {
        type: "emote",
        texture: "ammo-12gauge.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo762mm: {
        type: "emote",
        texture: "ammo-762mm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo556mm: {
        type: "emote",
        texture: "ammo-556mm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo50ae: {
        type: "emote",
        texture: "ammo-50AE.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo308sub: {
        type: "emote",
        texture: "ammo-308sub.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammoflare: {
        type: "emote",
        texture: "ammo-flare.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo45acp: {
        type: "emote",
        texture: "ammo-45acp.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_loot: {
        type: "emote",
        texture: "",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_nothing: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_size: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_m9: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_03",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_chatty: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_02",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_drain: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_02",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_9mm: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_12g: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_556: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_762: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_super: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_bugle_inspiration_red: {
        type: "emote",
        texture: "bugle-inspiration-red.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
    emote_bugle_final_red: {
        type: "emote",
        texture: "bugle-final-red.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
    emote_bugle_inspiration_blue: {
        type: "emote",
        texture: "bugle-inspiration-blue.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
    emote_bugle_final_blue: {
        type: "emote",
        texture: "bugle-final-blue.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
        // standard issue emotes
    // faces
    emote_alienface: {
        type: "emote",
        name: "Alien Face",
        rarity: Rarity.Common,
        texture: "face-alien.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_angryface: {
        type: "emote",
        name: "Angry Face",
        rarity: Rarity.Common,
        texture: "face-angry.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_boffy: {
        type: "emote",
        name: "Boffy",
        rarity: Rarity.Common,
        texture: "face-boffy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_dabface: {
        type: "emote",
        name: "Dab Face",
        rarity: Rarity.Common,
        texture: "face-dab.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_disappointface: {
        type: "emote",
        name: "Disappointed Face",
        rarity: Rarity.Common,
        texture: "face-disappoint.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_happyface: {
        type: "emote",
        name: "Happy Face",
        rarity: Rarity.Common,
        texture: "face-happy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_headshotface: {
        type: "emote",
        name: "Headshot!",
        rarity: Rarity.Common,
        texture: "face-headshot.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_heartface: {
        type: "emote",
        name: "Heart Face",
        rarity: Rarity.Common,
        texture: "face-heart.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_impface: {
        type: "emote",
        name: "Imp Face",
        rarity: Rarity.Common,
        texture: "face-imp.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_joyface: {
        type: "emote",
        name: "Joyful Face",
        rarity: Rarity.Common,
        texture: "face-joy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_monocleface: {
        type: "emote",
        name: "Monocle Face",
        rarity: Rarity.Common,
        texture: "face-monocle.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_sadface: {
        type: "emote",
        name: "Sad Face",
        rarity: Rarity.Common,
        texture: "face-sad.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_sobface: {
        type: "emote",
        name: "Sobbing Face",
        rarity: Rarity.Common,
        texture: "face-sob.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_sunglassface: {
        type: "emote",
        name: "Sunglasses Face",
        rarity: Rarity.Common,
        texture: "face-sunglass.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_thinkingface: {
        type: "emote",
        name: "Thonk",
        rarity: Rarity.Common,
        texture: "face-thinking.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_upsidedownface: {
        type: "emote",
        name: "Upside Down Face",
        rarity: Rarity.Common,
        texture: "face-upsidedown.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    // food
    emote_acorn: {
        type: "emote",
        name: "Acorn",
        rarity: Rarity.Common,
        texture: "acorn.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_baguette: {
        type: "emote",
        name: "Baguette",
        rarity: Rarity.Common,
        texture: "baguette.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_cake: {
        type: "emote",
        name: "Cake",
        rarity: Rarity.Common,
        texture: "cake.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_candycorn: {
        type: "emote",
        name: "Candy Corn",
        rarity: Rarity.Common,
        texture: "candy-corn.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_chickendinner: {
        type: "emote",
        name: "Chicken Dinner",
        rarity: Rarity.Common,
        texture: "chicken-dinner.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_coconut: {
        type: "emote",
        name: "Coconut",
        rarity: Rarity.Common,
        texture: "coconut.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_cupcake: {
        type: "emote",
        name: "Cupcake",
        rarity: Rarity.Common,
        texture: "cupcake.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_donut: {
        type: "emote",
        name: "Donut",
        rarity: Rarity.Common,
        texture: "donut.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_eggplant: {
        type: "emote",
        name: "Eggplant",
        rarity: Rarity.Common,
        texture: "eggplant.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_icecream: {
        type: "emote",
        name: "Ice Cream",
        rarity: Rarity.Common,
        texture: "ice-cream.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_leek: {
        type: "emote",
        name: "Leek",
        rarity: Rarity.Common,
        texture: "leek.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_pineapple: {
        type: "emote",
        name: "Pineapple",
        rarity: Rarity.Common,
        texture: "pineapple.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_tomato: {
        type: "emote",
        name: "Tomato",
        rarity: Rarity.Common,
        texture: "tomato.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_potato: {
        type: "emote",
        name: "Potato",
        rarity: Rarity.Common,
        texture: "potato.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_salt: {
        type: "emote",
        name: "Salt Shaker",
        rarity: Rarity.Common,
        texture: "salt.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    // animals
    emote_cattle: {
        type: "emote",
        name: "Cattle Skull",
        rarity: Rarity.Common,
        texture: "cattle.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_chick: {
        type: "emote",
        name: "Chick",
        rarity: Rarity.Common,
        texture: "chick.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_crab: {
        type: "emote",
        name: "Crab",
        rarity: Rarity.Common,
        texture: "crab.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_fish: {
        type: "emote",
        name: "Fish",
        rarity: Rarity.Common,
        texture: "fish.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_turkeyanimal: {
        type: "emote",
        name: "Turkey",
        rarity: Rarity.Common,
        texture: "turkey-animal.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_whale: {
        type: "emote",
        name: "Whale",
        rarity: Rarity.Common,
        texture: "whale.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    // logos
    emote_police: {
        type: "emote",
        name: "Police Insignia",
        rarity: Rarity.Common,
        texture: "police.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logosurviv: {
        type: "emote",
        name: "PARMA",
        rarity: Rarity.Common,
        texture: "logo-surviv.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_surviv: {
        type: "emote",
        name: "Surviv Logo",
        rarity: Rarity.Common,
        texture: "surviv.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logocaduceus: {
        type: "emote",
        name: "The Caduceus",
        rarity: Rarity.Common,
        texture: "logo-caduceus.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logochrysanthemum: {
        type: "emote",
        name: "The Chrysanthemum",
        rarity: Rarity.Common,
        texture: "logo-chrysanthemum.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logocloud: {
        type: "emote",
        name: "The Cloud",
        rarity: Rarity.Common,
        texture: "logo-cloud.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logoconch: {
        type: "emote",
        name: "The Conch",
        rarity: Rarity.Common,
        texture: "logo-conch.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logocrossing: {
        type: "emote",
        name: "The Crossing",
        rarity: Rarity.Common,
        texture: "logo-crossing.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logoegg: {
        type: "emote",
        name: "The Egg",
        rarity: Rarity.Common,
        texture: "logo-egg.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logometeor: {
        type: "emote",
        name: "The Meteor",
        rarity: Rarity.Common,
        texture: "logo-meteor.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logohatchet: {
        type: "emote",
        name: "The Hatchet",
        rarity: Rarity.Common,
        texture: "logo-hatchet.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logohydra: {
        type: "emote",
        name: "The Hydra",
        rarity: Rarity.Common,
        texture: "logo-hydra.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logostorm: {
        type: "emote",
        name: "The Storm",
        rarity: Rarity.Common,
        texture: "logo-storm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logoswine: {
        type: "emote",
        name: "The Swine",
        rarity: Rarity.Common,
        texture: "logo-swine.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logotwins: {
        type: "emote",
        name: "The Twins",
        rarity: Rarity.Common,
        texture: "logo-twins.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    // other
    emote_campfire: {
        type: "emote",
        name: "Campfire",
        rarity: Rarity.Common,
        texture: "campfire.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_egg: {
        type: "emote",
        name: "Egg",
        rarity: Rarity.Common,
        texture: "egg.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_flex: {
        type: "emote",
        name: "Flex",
        rarity: Rarity.Common,
        texture: "flex.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_forest: {
        type: "emote",
        name: "Forest",
        rarity: Rarity.Common,
        texture: "forest.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_gg: {
        type: "emote",
        name: "GG",
        rarity: Rarity.Common,
        texture: "gg.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_heart: {
        type: "emote",
        name: "Heart",
        rarity: Rarity.Common,
        texture: "heart.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_leaf: {
        type: "emote",
        name: "Leaf",
        rarity: Rarity.Common,
        texture: "leaf.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_pilgrimhat: {
        type: "emote",
        name: "Pilgrim",
        rarity: Rarity.Common,
        texture: "pilgrim-hat.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_pumpkin: {
        type: "emote",
        name: "Pumpkin",
        rarity: Rarity.Common,
        texture: "pumpkin.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_question: {
        type: "emote",
        name: "Question Mark",
        rarity: Rarity.Common,
        texture: "question.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_santahat: {
        type: "emote",
        name: "Santa Hat",
        rarity: Rarity.Common,
        texture: "santa-hat.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_snowflake: {
        type: "emote",
        name: "Snowflake",
        rarity: Rarity.Common,
        texture: "snowflake.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_snowman: {
        type: "emote",
        name: "Snowman",
        rarity: Rarity.Common,
        texture: "snowman.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_teabag: {
        type: "emote",
        name: "Teabag",
        rarity: Rarity.Common,
        texture: "teabag.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_thumbsup: {
        type: "emote",
        name: "Thumbs Up",
        rarity: Rarity.Common,
        texture: "thumbs-up.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_tombstone: {
        type: "emote",
        name: "Tombstone",
        rarity: Rarity.Common,
        texture: "tombstone.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_trunk: {
        type: "emote",
        name: "Tree Trunk",
        rarity: Rarity.Common,
        texture: "trunk.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_sleepy: {
        type: "emote",
        name: "Zzz",
        rarity: Rarity.Common,
        texture: "sleepy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    // country flags
    emote_flagalbania: {
        type: "emote",
        name: "Flag Albania",
        rarity: Rarity.Common,
        texture: "flag-albania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagalgeria: {
        type: "emote",
        name: "Flag Algeria",
        rarity: Rarity.Common,
        texture: "flag-algeria.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagandorra: {
        type: "emote",
        name: "Flag Andorra",
        rarity: Rarity.Common,
        texture: "flag-andorra.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagangola: {
        type: "emote",
        name: "Flag Angola",
        rarity: Rarity.Common,
        texture: "flag-angola.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagantigua: {
        type: "emote",
        name: "Flag Antigua",
        rarity: Rarity.Common,
        texture: "flag-antigua-and-barbuda.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagargentina: {
        type: "emote",
        name: "Flag Argentina",
        rarity: Rarity.Common,
        texture: "flag-argentina.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagarmenia: {
        type: "emote",
        name: "Flag Armenia",
        rarity: Rarity.Common,
        texture: "flag-armenia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagaustralia: {
        type: "emote",
        name: "Flag Australia",
        rarity: Rarity.Common,
        texture: "flag-australia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagaustria: {
        type: "emote",
        name: "Flag Austria",
        rarity: Rarity.Common,
        texture: "flag-austria.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagazerbaijan: {
        type: "emote",
        name: "Flag Azerbaijan",
        rarity: Rarity.Common,
        texture: "flag-azerbaijan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbahamas: {
        type: "emote",
        name: "Flag Bahamas",
        rarity: Rarity.Common,
        texture: "flag-the-bahamas.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbahrain: {
        type: "emote",
        name: "Flag Bahrain",
        rarity: Rarity.Common,
        texture: "flag-bahrain.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbangladesh: {
        type: "emote",
        name: "Flag Bangladesh",
        rarity: Rarity.Common,
        texture: "flag-bangladesh.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbarbados: {
        type: "emote",
        name: "Flag Barbados",
        rarity: Rarity.Common,
        texture: "flag-barbados.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbelarus: {
        type: "emote",
        name: "Flag Belarus",
        rarity: Rarity.Common,
        texture: "flag-belarus.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbelgium: {
        type: "emote",
        name: "Flag Belgium",
        rarity: Rarity.Common,
        texture: "flag-belgium.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbenin: {
        type: "emote",
        name: "Flag Benin",
        rarity: Rarity.Common,
        texture: "flag-benin.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbolivia: {
        type: "emote",
        name: "Flag Bolivia",
        rarity: Rarity.Common,
        texture: "flag-bolivia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbosnia: {
        type: "emote",
        name: "Flag Bosnia",
        rarity: Rarity.Common,
        texture: "flag-bosnia-and-herzegovina.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbotswana: {
        type: "emote",
        name: "Flag Botswana",
        rarity: Rarity.Common,
        texture: "flag-botswana.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbrazil: {
        type: "emote",
        name: "Flag Brazil",
        rarity: Rarity.Common,
        texture: "flag-brazil.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbulgaria: {
        type: "emote",
        name: "Flag Bulgaria",
        rarity: Rarity.Common,
        texture: "flag-bulgaria.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagburkinafaso: {
        type: "emote",
        name: "Flag Burkina Faso",
        rarity: Rarity.Common,
        texture: "flag-burkina-faso.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagburundi: {
        type: "emote",
        name: "Flag Burundi",
        rarity: Rarity.Common,
        texture: "flag-burundi.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcameroon: {
        type: "emote",
        name: "Flag Cameroon",
        rarity: Rarity.Common,
        texture: "flag-cameroon.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcanada: {
        type: "emote",
        name: "Flag Canada",
        rarity: Rarity.Common,
        texture: "flag-canada.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcar: {
        type: "emote",
        name: "Flag CAR",
        rarity: Rarity.Common,
        texture: "flag-central-african-republic.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagchad: {
        type: "emote",
        name: "Flag Chad",
        rarity: Rarity.Common,
        texture: "flag-chad.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagchile: {
        type: "emote",
        name: "Flag Chile",
        rarity: Rarity.Common,
        texture: "flag-chile.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagchina: {
        type: "emote",
        name: "Flag China",
        rarity: Rarity.Common,
        texture: "flag-china.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcolombia: {
        type: "emote",
        name: "Flag Colombia",
        rarity: Rarity.Common,
        texture: "flag-colombia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcomoros: {
        type: "emote",
        name: "Flag Comoros",
        rarity: Rarity.Common,
        texture: "flag-comoros.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcongo: {
        type: "emote",
        name: "Flag Congo",
        rarity: Rarity.Common,
        texture: "flag-congo.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcostarica: {
        type: "emote",
        name: "Flag Costa Rica",
        rarity: Rarity.Common,
        texture: "flag-costa-rica.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcroatia: {
        type: "emote",
        name: "Flag Croatia",
        rarity: Rarity.Common,
        texture: "flag-croatia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcuba: {
        type: "emote",
        name: "Flag Cuba",
        rarity: Rarity.Common,
        texture: "flag-cuba.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagczechia: {
        type: "emote",
        name: "Flag Czechia",
        rarity: Rarity.Common,
        texture: "flag-czech-republic.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagdrcongo: {
        type: "emote",
        name: "Flag DR Congo",
        rarity: Rarity.Common,
        texture: "flag-democratic-republic-of-the-congo.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagdenmark: {
        type: "emote",
        name: "Flag Denmark",
        rarity: Rarity.Common,
        texture: "flag-denmark.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagdjibouti: {
        type: "emote",
        name: "Flag Djibouti",
        rarity: Rarity.Common,
        texture: "flag-djibouti.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagdominicanrepublic: {
        type: "emote",
        name: "Flag Dominican Republic",
        rarity: Rarity.Common,
        texture: "flag-dominican-republic.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagecuador: {
        type: "emote",
        name: "Flag Ecuador",
        rarity: Rarity.Common,
        texture: "flag-ecuador.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagegypt: {
        type: "emote",
        name: "Flag Egypt",
        rarity: Rarity.Common,
        texture: "flag-egypt.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagelsalvador: {
        type: "emote",
        name: "Flag El Salvador",
        rarity: Rarity.Common,
        texture: "flag-el-salvador.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagestonia: {
        type: "emote",
        name: "Flag Estonia",
        rarity: Rarity.Common,
        texture: "flag-estonia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagethiopia: {
        type: "emote",
        name: "Flag Ethiopia",
        rarity: Rarity.Common,
        texture: "flag-ethiopia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagfaroeislands: {
        type: "emote",
        name: "Flag Faroe Islands",
        rarity: Rarity.Common,
        texture: "flag-faroe-islands.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagfiji: {
        type: "emote",
        name: "Flag Fiji",
        rarity: Rarity.Common,
        texture: "flag-fiji.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagfinland: {
        type: "emote",
        name: "Flag Finland",
        rarity: Rarity.Common,
        texture: "flag-finland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagfrance: {
        type: "emote",
        name: "Flag France",
        rarity: Rarity.Common,
        texture: "flag-france.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggabon: {
        type: "emote",
        name: "Flag Gabon",
        rarity: Rarity.Common,
        texture: "flag-gabon.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggambia: {
        type: "emote",
        name: "Flag Gambia",
        rarity: Rarity.Common,
        texture: "flag-the-gambia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggeorgia: {
        type: "emote",
        name: "Flag Georgia",
        rarity: Rarity.Common,
        texture: "flag-georgia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggermany: {
        type: "emote",
        name: "Flag Germany",
        rarity: Rarity.Common,
        texture: "flag-germany.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagghana: {
        type: "emote",
        name: "Flag Ghana",
        rarity: Rarity.Common,
        texture: "flag-ghana.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggreece: {
        type: "emote",
        name: "Flag Greece",
        rarity: Rarity.Common,
        texture: "flag-greece.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggreenland: {
        type: "emote",
        name: "Flag Greenland",
        rarity: Rarity.Common,
        texture: "flag-greenland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggrenada: {
        type: "emote",
        name: "Flag Grenada",
        rarity: Rarity.Common,
        texture: "flag-grenada.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagguatemala: {
        type: "emote",
        name: "Flag Guatemala",
        rarity: Rarity.Common,
        texture: "flag-guatemala.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagguineabissau: {
        type: "emote",
        name: "Flag Guinea-Bissau",
        rarity: Rarity.Common,
        texture: "flag-guinea-bissau.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagguinea: {
        type: "emote",
        name: "Flag Guinea",
        rarity: Rarity.Common,
        texture: "flag-guinea.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagguyana: {
        type: "emote",
        name: "Flag Guyana",
        rarity: Rarity.Common,
        texture: "flag-guyana.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaghonduras: {
        type: "emote",
        name: "Flag Honduras",
        rarity: Rarity.Common,
        texture: "flag-honduras.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaghongkong: {
        type: "emote",
        name: "Flag Hong Kong",
        rarity: Rarity.Common,
        texture: "flag-hong-kong.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaghungary: {
        type: "emote",
        name: "Flag Hungary",
        rarity: Rarity.Common,
        texture: "flag-hungary.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagiceland: {
        type: "emote",
        name: "Flag Iceland",
        rarity: Rarity.Common,
        texture: "flag-iceland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagindia: {
        type: "emote",
        name: "Flag India",
        rarity: Rarity.Common,
        texture: "flag-india.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagindonesia: {
        type: "emote",
        name: "Flag Indonesia",
        rarity: Rarity.Common,
        texture: "flag-indonesia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagiran: {
        type: "emote",
        name: "Flag Iran",
        rarity: Rarity.Common,
        texture: "flag-iran.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagireland: {
        type: "emote",
        name: "Flag Ireland",
        rarity: Rarity.Common,
        texture: "flag-ireland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagitaly: {
        type: "emote",
        name: "Flag Italy",
        rarity: Rarity.Common,
        texture: "flag-italy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagivorycoast: {
        type: "emote",
        name: "Flag Ivory Coast",
        rarity: Rarity.Common,
        texture: "flag-ivory-coast.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagjamaica: {
        type: "emote",
        name: "Flag Jamaica",
        rarity: Rarity.Common,
        texture: "flag-jamaica.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagjapan: {
        type: "emote",
        name: "Flag Japan",
        rarity: Rarity.Common,
        texture: "flag-japan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagjordan: {
        type: "emote",
        name: "Flag Jordan",
        rarity: Rarity.Common,
        texture: "flag-jordan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagkazakhstan: {
        type: "emote",
        name: "Flag Kazakhstan",
        rarity: Rarity.Common,
        texture: "flag-kazakhstan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagkenya: {
        type: "emote",
        name: "Flag Kenya",
        rarity: Rarity.Common,
        texture: "flag-kenya.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagkiribati: {
        type: "emote",
        name: "Flag Kiribati",
        rarity: Rarity.Common,
        texture: "flag-kiribati.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagkuwait: {
        type: "emote",
        name: "Flag Kuwait",
        rarity: Rarity.Common,
        texture: "flag-kuwait.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglaos: {
        type: "emote",
        name: "Flag Laos",
        rarity: Rarity.Common,
        texture: "flag-laos.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglatvia: {
        type: "emote",
        name: "Flag Latvia",
        rarity: Rarity.Common,
        texture: "flag-latvia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglebanon: {
        type: "emote",
        name: "Flag Lebanon",
        rarity: Rarity.Common,
        texture: "flag-lebanon.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglesotho: {
        type: "emote",
        name: "Flag Lesotho",
        rarity: Rarity.Common,
        texture: "flag-lesotho.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagliberia: {
        type: "emote",
        name: "Flag Liberia",
        rarity: Rarity.Common,
        texture: "flag-liberia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglibya: {
        type: "emote",
        name: "Flag Libya",
        rarity: Rarity.Common,
        texture: "flag-libya.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagliechtenstein: {
        type: "emote",
        name: "Flag Liechtenstein",
        rarity: Rarity.Common,
        texture: "flag-liechtenstein.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglithuania: {
        type: "emote",
        name: "Flag Lithuania",
        rarity: Rarity.Common,
        texture: "flag-lithuania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagluxembourg: {
        type: "emote",
        name: "Flag Luxembourg",
        rarity: Rarity.Common,
        texture: "flag-luxembourg.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmadagascar: {
        type: "emote",
        name: "Flag Madagascar",
        rarity: Rarity.Common,
        texture: "flag-madagascar.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmalaysia: {
        type: "emote",
        name: "Flag Malaysia",
        rarity: Rarity.Common,
        texture: "flag-malaysia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmaldives: {
        type: "emote",
        name: "Flag Maldives",
        rarity: Rarity.Common,
        texture: "flag-maldives.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmali: {
        type: "emote",
        name: "Flag Mali",
        rarity: Rarity.Common,
        texture: "flag-mali.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmauritania: {
        type: "emote",
        name: "Flag Mauritania",
        rarity: Rarity.Common,
        texture: "flag-mauritania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmauritius: {
        type: "emote",
        name: "Flag Mauritius",
        rarity: Rarity.Common,
        texture: "flag-mauritius.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmexico: {
        type: "emote",
        name: "Flag Mexico",
        rarity: Rarity.Common,
        texture: "flag-mexico.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmicronesia: {
        type: "emote",
        name: "Flag Micronesia",
        rarity: Rarity.Common,
        texture: "flag-micronesia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmoldova: {
        type: "emote",
        name: "Flag Moldova",
        rarity: Rarity.Common,
        texture: "flag-moldova.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmonaco: {
        type: "emote",
        name: "Flag Monaco",
        rarity: Rarity.Common,
        texture: "flag-monaco.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmorocco: {
        type: "emote",
        name: "Flag Morocco",
        rarity: Rarity.Common,
        texture: "flag-morocco.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmyanmar: {
        type: "emote",
        name: "Flag Myanmar",
        rarity: Rarity.Common,
        texture: "flag-myanmar.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnamibia: {
        type: "emote",
        name: "Flag Namibia",
        rarity: Rarity.Common,
        texture: "flag-namibia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnauru: {
        type: "emote",
        name: "Flag Nauru",
        rarity: Rarity.Common,
        texture: "flag-nauru.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnetherlands: {
        type: "emote",
        name: "Flag Netherlands",
        rarity: Rarity.Common,
        texture: "flag-netherlands.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnewzealand: {
        type: "emote",
        name: "Flag New Zealand",
        rarity: Rarity.Common,
        texture: "flag-new-zealand.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnicaragua: {
        type: "emote",
        name: "Flag Nicaragua",
        rarity: Rarity.Common,
        texture: "flag-nicaragua.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagniger: {
        type: "emote",
        name: "Flag Niger",
        rarity: Rarity.Common,
        texture: "flag-niger.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnigeria: {
        type: "emote",
        name: "Flag Nigeria",
        rarity: Rarity.Common,
        texture: "flag-nigeria.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnorthmacedonia: {
        type: "emote",
        name: "Flag North Macedonia",
        rarity: Rarity.Common,
        texture: "flag-north-macedonia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnorway: {
        type: "emote",
        name: "Flag Norway",
        rarity: Rarity.Common,
        texture: "flag-norway.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagoman: {
        type: "emote",
        name: "Flag Oman",
        rarity: Rarity.Common,
        texture: "flag-oman.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpakistan: {
        type: "emote",
        name: "Flag Pakistan",
        rarity: Rarity.Common,
        texture: "flag-pakistan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpalau: {
        type: "emote",
        name: "Flag Palau",
        rarity: Rarity.Common,
        texture: "flag-palau.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpalestine: {
        type: "emote",
        name: "Flag Palestine",
        rarity: Rarity.Common,
        texture: "flag-palestine.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpanama: {
        type: "emote",
        name: "Flag Panama",
        rarity: Rarity.Common,
        texture: "flag-panama.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagparaguay: {
        type: "emote",
        name: "Flag Paraguay",
        rarity: Rarity.Common,
        texture: "flag-paraguay.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagperu: {
        type: "emote",
        name: "Flag Peru",
        rarity: Rarity.Common,
        texture: "flag-peru.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagphilippines: {
        type: "emote",
        name: "Flag Philippines",
        rarity: Rarity.Common,
        texture: "flag-philippines.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpoland: {
        type: "emote",
        name: "Flag Poland",
        rarity: Rarity.Common,
        texture: "flag-poland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagportugal: {
        type: "emote",
        name: "Flag Portugal",
        rarity: Rarity.Common,
        texture: "flag-portugal.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagqatar: {
        type: "emote",
        name: "Flag Qatar",
        rarity: Rarity.Common,
        texture: "flag-qatar.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagromania: {
        type: "emote",
        name: "Flag Romania",
        rarity: Rarity.Common,
        texture: "flag-romania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagrussia: {
        type: "emote",
        name: "Flag Russia",
        rarity: Rarity.Common,
        texture: "flag-russia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagrwanda: {
        type: "emote",
        name: "Flag Rwanda",
        rarity: Rarity.Common,
        texture: "flag-rwanda.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsaintkitts: {
        type: "emote",
        name: "Flag Saint Kitts",
        rarity: Rarity.Common,
        texture: "flag-saint-kitts-and-nevis.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsaintlucia: {
        type: "emote",
        name: "Flag Saint Lucia",
        rarity: Rarity.Common,
        texture: "flag-saint-lucia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsaintvincent: {
        type: "emote",
        name: "Flag Saint Vincent",
        rarity: Rarity.Common,
        texture: "flag-saint-vincent-and-the-grenadines.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsamoa: {
        type: "emote",
        name: "Flag Samoa",
        rarity: Rarity.Common,
        texture: "flag-samoa.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsaotome: {
        type: "emote",
        name: "Flag São Tomé",
        rarity: Rarity.Common,
        texture: "flag-sao-tome-and-principe.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsenegal: {
        type: "emote",
        name: "Flag Senegal",
        rarity: Rarity.Common,
        texture: "flag-senegal.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagserbia: {
        type: "emote",
        name: "Flag Serbia",
        rarity: Rarity.Common,
        texture: "flag-serbia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagseychelles: {
        type: "emote",
        name: "Flag Seychelles",
        rarity: Rarity.Common,
        texture: "flag-seychelles.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsierraleone: {
        type: "emote",
        name: "Flag Sierra Leone",
        rarity: Rarity.Common,
        texture: "flag-sierra-leone.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsingapore: {
        type: "emote",
        name: "Flag Singapore",
        rarity: Rarity.Common,
        texture: "flag-singapore.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagslovakia: {
        type: "emote",
        name: "Flag Slovakia",
        rarity: Rarity.Common,
        texture: "flag-slovakia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagslovenia: {
        type: "emote",
        name: "Flag Slovenia",
        rarity: Rarity.Common,
        texture: "flag-slovenia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsolomonislands: {
        type: "emote",
        name: "Flag Solomon Islands",
        rarity: Rarity.Common,
        texture: "flag-solomon-islands.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsomalia: {
        type: "emote",
        name: "Flag Somalia",
        rarity: Rarity.Common,
        texture: "flag-somalia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsouthafrica: {
        type: "emote",
        name: "Flag South Africa",
        rarity: Rarity.Common,
        texture: "flag-south-africa.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsouthkorea: {
        type: "emote",
        name: "Flag South Korea",
        rarity: Rarity.Common,
        texture: "flag-south-korea.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsouthsudan: {
        type: "emote",
        name: "Flag South Sudan",
        rarity: Rarity.Common,
        texture: "flag-south-sudan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagspain: {
        type: "emote",
        name: "Flag Spain",
        rarity: Rarity.Common,
        texture: "flag-spain.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsudan: {
        type: "emote",
        name: "Flag Sudan",
        rarity: Rarity.Common,
        texture: "flag-sudan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsuriname: {
        type: "emote",
        name: "Flag Suriname",
        rarity: Rarity.Common,
        texture: "flag-suriname.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsweden: {
        type: "emote",
        name: "Flag Sweden",
        rarity: Rarity.Common,
        texture: "flag-sweden.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagswitzerland: {
        type: "emote",
        name: "Flag Switzerland",
        rarity: Rarity.Common,
        texture: "flag-switzerland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsyria: {
        type: "emote",
        name: "Flag Syria",
        rarity: Rarity.Common,
        texture: "flag-syria.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtaiwan: {
        type: "emote",
        name: "Flag Taiwan",
        rarity: Rarity.Common,
        texture: "flag-taiwan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtanzania: {
        type: "emote",
        name: "Flag Tanzania",
        rarity: Rarity.Common,
        texture: "flag-tanzania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagthailand: {
        type: "emote",
        name: "Flag Thailand",
        rarity: Rarity.Common,
        texture: "flag-thailand.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtimorleste: {
        type: "emote",
        name: "Flag Timor Leste",
        rarity: Rarity.Common,
        texture: "flag-timor-leste.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtogo: {
        type: "emote",
        name: "Flag Togo",
        rarity: Rarity.Common,
        texture: "flag-togo.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtonga: {
        type: "emote",
        name: "Flag Tonga",
        rarity: Rarity.Common,
        texture: "flag-tonga.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtrinidad: {
        type: "emote",
        name: "Flag Trinidad and Tobago",
        rarity: Rarity.Common,
        texture: "flag-trinidad-and-tobago.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtunisia: {
        type: "emote",
        name: "Flag Tunisia",
        rarity: Rarity.Common,
        texture: "flag-tunisia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagturkey: {
        type: "emote",
        name: "Flag Turkey",
        rarity: Rarity.Common,
        texture: "flag-turkey.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtuvalu: {
        type: "emote",
        name: "Flag Tuvalu",
        rarity: Rarity.Common,
        texture: "flag-tuvalu.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagukraine: {
        type: "emote",
        name: "Flag Ukraine",
        rarity: Rarity.Common,
        texture: "flag-ukraine.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaguae: {
        type: "emote",
        name: "Flag United Arab Emirates",
        rarity: Rarity.Common,
        texture: "flag-united-arab-emirates.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaguk: {
        type: "emote",
        name: "Flag United Kingdom",
        rarity: Rarity.Common,
        texture: "flag-united-kingdom.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagus: {
        type: "emote",
        name: "Flag United States",
        rarity: Rarity.Common,
        texture: "flag-united-states-of-america.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaguruguay: {
        type: "emote",
        name: "Flag Uruguay",
        rarity: Rarity.Common,
        texture: "flag-uruguay.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaguzbekistan: {
        type: "emote",
        name: "Flag Uzbekistan",
        rarity: Rarity.Common,
        texture: "flag-uzbekistan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagvenezuela: {
        type: "emote",
        name: "Flag Venezuela",
        rarity: Rarity.Common,
        texture: "flag-venezuela.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagvietnam: {
        type: "emote",
        name: "Flag Vietnam",
        rarity: Rarity.Common,
        texture: "flag-vietnam.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagyemen: {
        type: "emote",
        name: "Flag Yemen",
        rarity: Rarity.Common,
        texture: "flag-yemen.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    // pride flags
    emote_flagpride: {
        type: "emote",
        name: "Flag Pride",
        rarity: Rarity.Common,
        texture: "flag-pride.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagasexual: {
        type: "emote",
        name: "Flag Asexual",
        rarity: Rarity.Common,
        texture: "flag-asexual.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbisexual: {
        type: "emote",
        name: "Flag Bisexual",
        rarity: Rarity.Common,
        texture: "flag-bisexual.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggay: {
        type: "emote",
        name: "Flag Gay",
        rarity: Rarity.Common,
        texture: "flag-gay.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglesbian: {
        type: "emote",
        name: "Flag Lesbian",
        rarity: Rarity.Common,
        texture: "flag-lesbian.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnonbinary: {
        type: "emote",
        name: "Flag Non-Binary",
        rarity: Rarity.Common,
        texture: "flag-nonbinary.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtransgender: {
        type: "emote",
        name: "Flag Transgender",
        rarity: Rarity.Common,
        texture: "flag-transgender.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
        // Survevr Pass 1 emotes
    emote_bandagedface: {
        type: "emote",
        name: "Bandaged Face",
        rarity: Rarity.Uncommon,
        texture: "face-bandaged.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_ok: {
        type: "emote",
        name: "Ok",
        rarity: Rarity.Uncommon,
        texture: "ok.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_pooface: {
        type: "emote",
        name: "Poo Face",
        rarity: Rarity.Rare,
        texture: "face-poo.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_ghost_base: {
        type: "emote",
        name: "Ghost",
        rarity: Rarity.Uncommon,
        texture: "ghost-base.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_picassoface: {
        type: "emote",
        name: "Picasso Face",
        rarity: Rarity.Uncommon,
        texture: "face-picasso.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_rainbow: {
        type: "emote",
        name: "Rainbow",
        rarity: Rarity.Rare,
        texture: "rainbow.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
};
